### Numpy (arithm. ops, indexing, slicing, reshaping, built-in methods, sorting, etc.)
### Pandas (loc, iloc, category type, etc.)

In [1]:
import numpy as np

In [2]:
# creating 2x3 numpy array from random digits, normally distributed
np.random.randn(2, 3)

array([[-0.84894714,  0.46964471, -1.02034134],
       [ 0.68333774,  1.06104632,  0.35099483]])

In [3]:
array_1 = np.random.randn(2, 3)

In [7]:
# main params
print("Shape:\t\t", array_1.shape)
print("Size:\t\t", array_1.size)
print("Data type:\t", array_1.dtype)
print("Dimensions:\t", array_1.ndim)

Shape:		 (2, 3)
Size:		 6
Data type:	 float64
Dimensions:	 2

In [9]:
# creating numpy array from a list
np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
# create a zero vector
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
# identity matrix
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
# creating some points
np.arange(start=-1, stop=1, step=0.1)

array([-1.00000000e+00, -9.00000000e-01, -8.00000000e-01, -7.00000000e-01,
       -6.00000000e-01, -5.00000000e-01, -4.00000000e-01, -3.00000000e-01,
       -2.00000000e-01, -1.00000000e-01, -2.22044605e-16,  1.00000000e-01,
        2.00000000e-01,  3.00000000e-01,  4.00000000e-01,  5.00000000e-01,
        6.00000000e-01,  7.00000000e-01,  8.00000000e-01,  9.00000000e-01])

In [19]:
# we can explicitly define data type for an array. we can convert with .astype() method as well
np.array([1, 2, 3], dtype=np.float64)

array([1., 2., 3.])

In [20]:
# basic arithm. ops
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [22]:
# every element is multiplie by itself, or by a specified digit
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [23]:
arr * 100

array([[100., 200., 300.],
       [400., 500., 600.]])

In [26]:
# typical scalar vector ops from linear algebra are available for matices and vectors
arr_1 = np.array([[1, 4], [4, 4], [3, 3]])
arr_2 = np.array([2, 2])

In [27]:
# scalar sum
arr_1 @ arr_2

array([10, 16, 12])

In [28]:
arr_1.dot(arr_2)

array([10, 16, 12])

In [29]:
# 3d arrays, (4, 3, 2)
array_3d = np.array([
    [[7, 1], [9, 4], [2, 3]],
    [[4, -1], [0, -1], [8, 0]],
    [[1, -1], [3, -1], [6, 9]],
    [[5, -1], [8, -1], [4, 7]]
])

In [30]:
array_3d

array([[[ 7,  1],
        [ 9,  4],
        [ 2,  3]],

       [[ 4, -1],
        [ 0, -1],
        [ 8,  0]],

       [[ 1, -1],
        [ 3, -1],
        [ 6,  9]],

       [[ 5, -1],
        [ 8, -1],
        [ 4,  7]]])

In [31]:
# accessing array's elements, getting a layer 3x2
array_3d[0]

array([[7, 1],
       [9, 4],
       [2, 3]])

In [32]:
# going deeper
array_3d[0][1]

array([9, 4])

In [33]:
array_3d[0][1][0]

np.int64(9)

In [35]:
# indexing in multidimensional array
array_2d = np.array([[3.5, 4, 6.5],
                     [.4, .9, 4.7],
                     [3.8, .4, -.3]])
array_2d

array([[ 3.5,  4. ,  6.5],
       [ 0.4,  0.9,  4.7],
       [ 3.8,  0.4, -0.3]])

In [37]:
# slicing [rows, columns]
array_2d[:, :]

array([[ 3.5,  4. ,  6.5],
       [ 0.4,  0.9,  4.7],
       [ 3.8,  0.4, -0.3]])

In [39]:
array_2d[:, -1:]

array([[ 6.5],
       [ 4.7],
       [-0.3]])

In [40]:
array_2d[1:2, -1:]

array([[4.7]])

In [41]:
# use .copy() method to work with temp dataframes and slices, otherwise original dataframe could be modified
# assign operator creates a link to original data!

In [43]:
# reshaping data with .reshape()
array = np.arange(32)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [45]:
# going from 1x32 to 2x16
array.reshape((2, 16))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]])

In [46]:
array.reshape((16, 2))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29],
       [30, 31]])

In [47]:
array.reshape(4, 2, 4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31]]])

In [48]:
# resize != reshape. resize modifies original data!

In [53]:
# matrix transposition - changing rows into columns, e.g. from 3x5 -> 5x3
array_for_tr = np.arange(15).reshape((3, 5))
array_for_tr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [52]:
# using T for transposition
array_for_tr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [54]:
# using .transpose() method, which allows more functionality
array_for_tr.transpose()

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [55]:
# e.g. we want to come from 2x2x4 -> 2x4x2, T won't allow this, we need .transpose()
array_2_2_4 = np.arange(16).reshape((2, 2, 4))
array_2_2_4

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [56]:
# you provide .transpose() with indexes of shape to be transformed
# (2, 2, 4) -> (2, 4, 2)
#  |  |  |
#  0  1  2 - indices
array_2_2_4.transpose((0, 2, 1))

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [57]:
array_2_2_4

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [68]:
# getting a sum of all array's elements, with .sum() method or built-in sum
array = np.random.randn(5, 4)
array

array([[-1.51436411,  1.01074201, -0.28759249,  1.49722599],
       [-1.78496957, -1.06649025,  0.36063618, -0.81500575],
       [ 1.67952927, -1.32803795,  1.13570287,  2.70616648],
       [-0.78827714, -0.19697282,  1.24630593,  0.52172551],
       [-0.6850059 ,  1.33029913,  2.00711517, -0.2372661 ]])

In [69]:
array.sum()

np.float64(4.791466467970519)

In [70]:
np.sum(array)

np.float64(4.791466467970519)

In [71]:
array.mean()

np.float64(0.23957332339852594)

In [72]:
# we can sum by axis as well
array = np.arange(12).reshape(2, 6)
array

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [74]:
# sum by rows
array.sum(axis=1)

array([15, 51])

In [75]:
# sum by columns. 
array.sum(axis=0)

array([ 6,  8, 10, 12, 14, 16])

In [76]:
# the same works for mean() and other math functions
array.mean(axis=0)

array([3., 4., 5., 6., 7., 8.])

In [77]:
# sorting arrays. method .sort() works in "inplace" mode, changing the source array
array = np.random.randn(6)
array

array([-1.05508887,  0.39983149,  0.39616551, -2.08806553,  0.53611063,
       -0.26575665])

In [78]:
array.sort()
array

array([-2.08806553, -1.05508887, -0.26575665,  0.39616551,  0.39983149,
        0.53611063])

In [79]:
# sorting works for axis as well\
array = np.array([[19, 8, 2], [3, 4, 5], [6, 3, 8]])
array

array([[19,  8,  2],
       [ 3,  4,  5],
       [ 6,  3,  8]])

In [80]:
# sorting by rows
array.sort(axis=1)
array

array([[ 2,  8, 19],
       [ 3,  4,  5],
       [ 3,  6,  8]])

### Pandas now - loc, iloc

In [81]:
import pandas as pd

In [82]:
data_df = pd.read_csv('data/covid-19-us-counties.csv')
data_df.head()

         date     county       state     fips  cases  deaths
0  2020-01-21  Snohomish  Washington  53061.0      1     0.0
1  2020-01-22  Snohomish  Washington  53061.0      1     0.0
2  2020-01-23  Snohomish  Washington  53061.0      1     0.0
3  2020-01-24       Cook    Illinois  17031.0      1     0.0
4  2020-01-24  Snohomish  Washington  53061.0      1     0.0

In [83]:
# loc method [rows, columns]. Rows are specified as names of indecies.
data_df.loc[:, :]

              date      county       state     fips  cases  deaths
0       2020-01-21   Snohomish  Washington  53061.0      1     0.0
1       2020-01-22   Snohomish  Washington  53061.0      1     0.0
2       2020-01-23   Snohomish  Washington  53061.0      1     0.0
3       2020-01-24        Cook    Illinois  17031.0      1     0.0
4       2020-01-24   Snohomish  Washington  53061.0      1     0.0
...            ...         ...         ...      ...    ...     ...
845872  2020-12-19  Sweetwater     Wyoming  56037.0   2702    15.0
845873  2020-12-19       Teton     Wyoming  56039.0   1992     2.0
845874  2020-12-19       Uinta     Wyoming  56041.0   1406     7.0
845875  2020-12-19    Washakie     Wyoming  56043.0    694    11.0
845876  2020-12-19      Weston     Wyoming  56045.0    443     2.0

[845877 rows x 6 columns]

In [84]:
data_df.loc[:, ['date', 'state']]

              date       state
0       2020-01-21  Washington
1       2020-01-22  Washington
2       2020-01-23  Washington
3       2020-01-24    Illinois
4       2020-01-24  Washington
...            ...         ...
845872  2020-12-19     Wyoming
845873  2020-12-19     Wyoming
845874  2020-12-19     Wyoming
845875  2020-12-19     Wyoming
845876  2020-12-19     Wyoming

[845877 rows x 2 columns]

In [85]:
data_df.loc[[1, 2, 3, 4], ['date', 'state']]

         date       state
1  2020-01-22  Washington
2  2020-01-23  Washington
3  2020-01-24    Illinois
4  2020-01-24  Washington

In [86]:
# ranges are well supported
data_df.loc[[1, 2, 3, 4], 'date': 'cases']

         date     county       state     fips  cases
1  2020-01-22  Snohomish  Washington  53061.0      1
2  2020-01-23  Snohomish  Washington  53061.0      1
3  2020-01-24       Cook    Illinois  17031.0      1
4  2020-01-24  Snohomish  Washington  53061.0      1

In [87]:
data_df.loc[10:15, 'date': 'cases']

          date       county       state     fips  cases
10  2020-01-26       Orange  California   6059.0      1
11  2020-01-26         Cook    Illinois  17031.0      1
12  2020-01-26    Snohomish  Washington  53061.0      1
13  2020-01-27     Maricopa     Arizona   4013.0      1
14  2020-01-27  Los Angeles  California   6037.0      1
15  2020-01-27       Orange  California   6059.0      1

In [89]:
# using indicies to display odd and even rows
data_df.loc[data_df.index % 2 == 0, :]

              date      county       state     fips  cases  deaths
0       2020-01-21   Snohomish  Washington  53061.0      1     0.0
2       2020-01-23   Snohomish  Washington  53061.0      1     0.0
4       2020-01-24   Snohomish  Washington  53061.0      1     0.0
6       2020-01-25        Cook    Illinois  17031.0      1     0.0
8       2020-01-26    Maricopa     Arizona   4013.0      1     0.0
...            ...         ...         ...      ...    ...     ...
845868  2020-12-19        Park     Wyoming  56029.0   1771     7.0
845870  2020-12-19    Sheridan     Wyoming  56033.0   2394    15.0
845872  2020-12-19  Sweetwater     Wyoming  56037.0   2702    15.0
845874  2020-12-19       Uinta     Wyoming  56041.0   1406     7.0
845876  2020-12-19      Weston     Wyoming  56045.0    443     2.0

[422939 rows x 6 columns]

In [90]:
# the same principle applies for columns
[i for i in data_df.columns]

['date', 'county', 'state', 'fips', 'cases', 'deaths']

In [91]:
data_df.loc[data_df.index % 2 == 0, 
            [i for i in data_df.columns if i.startswith('c')]]

            county  cases
0        Snohomish      1
2        Snohomish      1
4        Snohomish      1
6             Cook      1
8         Maricopa      1
...            ...    ...
845868        Park   1771
845870    Sheridan   2394
845872  Sweetwater   2702
845874       Uinta   1406
845876      Weston    443

[422939 rows x 2 columns]

In [92]:
# iloc() works in the same way, but requires positions instead of names for rows and columns
data_df.iloc[:7, 0:2]

         date     county
0  2020-01-21  Snohomish
1  2020-01-22  Snohomish
2  2020-01-23  Snohomish
3  2020-01-24       Cook
4  2020-01-24  Snohomish
5  2020-01-25     Orange
6  2020-01-25       Cook

In [96]:
# using Category type to save df's memory space, making its size smaller

In [94]:
data_df.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 845877 entries, 0 to 845876
Data columns (total 6 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   date    845877 non-null  object
 1   county  845877 non-null  object
 2   state   845877 non-null  object
 3   fips    837894 non-null  float64
 4   cases   845877 non-null  int64
 5   deaths  828052 non-null  float64
dtypes: float64(2), int64(1), object(3)
memory usage: 177.8 MB

In [95]:
data_df.memory_usage(deep=True)

Index          128
date      56673759
county    54301732
state     55141566
fips       6767016
cases      6767016
deaths     6767016
dtype: int64

In [98]:
data_df['state'].unique().size

55

In [100]:
# currently we have text field 'state' propagated over 845877 rows. We can convert this field to Category type
# to save some space. We will assign a number to each field, and will use this number in DF

In [102]:
data_df['state'] = data_df['state'].astype('category')

In [103]:
data_df['state'].head()

0    Washington
1    Washington
2    Washington
3      Illinois
4    Washington
Name: state, dtype: category
Categories (55, object): ['Alabama', 'Alaska', 'Arizona', 'Arkansas', ..., 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming']

In [104]:
data_df['state'].cat.codes.head()

0    51
1    51
2    51
3    14
4    51
dtype: int8

In [106]:
# checking how much space we saved: went down from 55141566 to 851611!
data_df.memory_usage(deep=True)

Index          128
date      56673759
county    54301732
state       851611
fips       6767016
cases      6767016
deaths     6767016
dtype: int64

In [109]:
# we save 98% of initial space!
1 - (851611 / 55141566)

0.984555915586438

In [110]:
# we can also use Category type for sorting. Instead of text fields describing network quality we'll assign a weight to 
# each text field, allowing adequate sorting. So we will have a logic within text fields.

In [113]:
# initial df with text field describing network quality
df = pd.DataFrame({'user_id': [1, 2, 3, 4, 5, 6, 7], 
                   'network_quality': ['good', 'very good', 'poor', 'excellent', 'bad', 'good', 'poor']})
df

   user_id network_quality
0        1            good
1        2       very good
2        3            poor
3        4       excellent
4        5             bad
5        6            good
6        7            poor

In [115]:
# sorting works but in a weird way - by letters
df.sort_values('network_quality')

   user_id network_quality
4        5             bad
3        4       excellent
0        1            good
5        6            good
2        3            poor
6        7            poor
1        2       very good

In [112]:
# creating a custom type for that
nq_type = pd.api.types.CategoricalDtype(categories=['bad', 'poor', 'good', 'very good','excellent'], ordered=True)

In [117]:
# converting our df's field into new custom category type
df['network_quality'] = df['network_quality'].astype(nq_type)

In [118]:
df

   user_id network_quality
0        1            good
1        2       very good
2        3            poor
3        4       excellent
4        5             bad
5        6            good
6        7            poor

In [125]:
# we see the logical link between category levels
df['network_quality'].head(10)

0         good
1    very good
2         poor
3    excellent
4          bad
5         good
6         poor
Name: network_quality, dtype: category
Categories (5, object): ['bad' < 'poor' < 'good' < 'very good' < 'excellent']

In [123]:
# now sorting works properly
df.sort_values('network_quality')

   user_id network_quality
4        5             bad
2        3            poor
6        7            poor
0        1            good
5        6            good
1        2       very good
3        4       excellent

In [126]:
# and we can use math operations with the category field now
df.loc[df['network_quality']>= 'good', :]

   user_id network_quality
0        1            good
1        2       very good
3        4       excellent
5        6            good