<h4 style="margin-bottom: 5px;">Pandas:</h4>

- GroupBy
- stack & unstack
- rolling, shift, sample
 - concatination of DataSets (concat, join, merge, etc)
 - .apply()
 - .to_datetime()
 - pivot vs pivot_table

In [1]:
import numpy as np
import pandas as pd

In [2]:
data_df = pd.read_csv('data/covid-19-us-counties.csv')

In [36]:
data_df.head()

         date     county       state     fips  cases  deaths
0  2020-01-21  Snohomish  Washington  53061.0      1     0.0
1  2020-01-22  Snohomish  Washington  53061.0      1     0.0
2  2020-01-23  Snohomish  Washington  53061.0      1     0.0
3  2020-01-24       Cook    Illinois  17031.0      1     0.0
4  2020-01-24  Snohomish  Washington  53061.0      1     0.0

In [4]:
data_df.groupby(['state'])['cases'].sum()

state
Alabama                      28136276
Alaska                        2312777
Arizona                      41273455
Arkansas                     15852022
California                  149716640
Colorado                     19563555
Connecticut                  15120897
Delaware                      4506920
District of Columbia          3311752
Florida                     123018142
Georgia                      54989563
Guam                           770612
Hawaii                        1879036
Idaho                         8979114
Illinois                     70923095
Indiana                      30061202
Iowa                         19974492
Kansas                       13373812
Kentucky                     15720961
Louisiana                    31537692
Maine                         1293817
Maryland                     25983970
Massachusetts                33253937
Michigan                     35975455
Minnesota                    24993450
Mississippi                  18047923
Missouri                     26645949
Montana                       4055066
Nebraska                     11194003
Nevada                       15710680
New Hampshire                 2244072
New Jersey                   51919989
New Mexico                    7950888
New York                    115355533
North Carolina               40200083
North Dakota                  5587709
Northern Mariana Islands        14058
Ohio                         36959975
Oklahoma                     17208285
Oregon                        7045153
Pennsylvania                 40058463
Puerto Rico                   8459824
Rhode Island                  6359172
South Carolina               25847015
South Dakota                  6056962
Tennessee                    37349820
Texas                       140038289
Utah                         16850473
Vermont                        478223
Virgin Islands                 192681
Virginia                     28913727
Washington                   19068061
West Virginia                 3734349
Wisconsin                    31930399
Wyoming                       2074782
Name: cases, dtype: int64

In [16]:
# .groupby() returns iterator with tuples, [0] contains the item we grouped by, [1] - DF for that item.
# e.g. for our grouping by states returns, [0] - state, [1] - DF for that state
for item in data_df.groupby(['state']):
    print(f'{item[0][0]}: {item[1]["cases"].sum():,}')

Alabama: 28,136,276
Alaska: 2,312,777
Arizona: 41,273,455
Arkansas: 15,852,022
California: 149,716,640
Colorado: 19,563,555
Connecticut: 15,120,897
Delaware: 4,506,920
District of Columbia: 3,311,752
Florida: 123,018,142
Georgia: 54,989,563
Guam: 770,612
Hawaii: 1,879,036
Idaho: 8,979,114
Illinois: 70,923,095
Indiana: 30,061,202
Iowa: 19,974,492
Kansas: 13,373,812
Kentucky: 15,720,961
Louisiana: 31,537,692
Maine: 1,293,817
Maryland: 25,983,970
Massachusetts: 33,253,937
Michigan: 35,975,455
Minnesota: 24,993,450
Mississippi: 18,047,923
Missouri: 26,645,949
Montana: 4,055,066
Nebraska: 11,194,003
Nevada: 15,710,680
New Hampshire: 2,244,072
New Jersey: 51,919,989
New Mexico: 7,950,888
New York: 115,355,533
North Carolina: 40,200,083
North Dakota: 5,587,709
Northern Mariana Islands: 14,058
Ohio: 36,959,975
Oklahoma: 17,208,285
Oregon: 7,045,153
Pennsylvania: 40,058,463
Puerto Rico: 8,459,824
Rhode Island: 6,359,172
South Carolina: 25,847,015
South Dakota: 6,056,962
Tennessee: 37,349,820
Texas: 140,038,289
Utah: 16,850,473
Vermont: 478,223
Virgin Islands: 192,681
Virginia: 28,913,727
Washington: 19,068,061
West Virginia: 3,734,349
Wisconsin: 31,930,399
Wyoming: 2,074,782

In [17]:
# grouping by 2+ fields. We'll have a unique comnination of 2+ fields in [0]
for item in data_df.groupby(['state', 'county']):
    print(f'{item[0]}: {item[1]["cases"].sum():,}')

('Alabama', 'Autauga'): 322,927
('Alabama', 'Baldwin'): 975,405
('Alabama', 'Barbour'): 157,947
('Alabama', 'Bibb'): 127,509
('Alabama', 'Blount'): 296,336
('Alabama', 'Bullock'): 110,097
('Alabama', 'Butler'): 184,473
('Alabama', 'Calhoun'): 631,510
('Alabama', 'Chambers'): 240,263
('Alabama', 'Cherokee'): 104,538
('Alabama', 'Chilton'): 257,438
('Alabama', 'Choctaw'): 67,979
('Alabama', 'Clarke'): 195,872
('Alabama', 'Clay'): 95,315
('Alabama', 'Cleburne'): 69,608
('Alabama', 'Coffee'): 264,610
('Alabama', 'Colbert'): 330,029
('Alabama', 'Conecuh'): 92,057
('Alabama', 'Coosa'): 35,824
('Alabama', 'Covington'): 249,887
('Alabama', 'Crenshaw'): 90,240
('Alabama', 'Cullman'): 414,665
('Alabama', 'Dale'): 255,181
('Alabama', 'Dallas'): 318,375
('Alabama', 'DeKalb'): 512,543
('Alabama', 'Elmore'): 491,754
('Alabama', 'Escambia'): 259,926
('Alabama', 'Etowah'): 660,673
('Alabama', 'Fayette'): 85,411
('Alabama', 'Franklin'): 340,664
('Alabama', 'Geneva'): 117,062
('Alabama', 'Greene'): 62,042
('Alabama', 'Hale'): 126,214
('Alabama', 'Henry'): 95,469
('Alabama', 'Houston'): 537,119
('Alabama', 'Jackson'): 321,597
('Alabama', 'Jefferson'): 3,653,783
('Alabama', 'Lamar'): 70,635
('Alabama', 'Lauderdale'): 378,692
('Alabama', 'Lawrence'): 123,705
('Alabama', 'Lee'): 945,557
('Alabama', 'Limestone'): 425,100
('Alabama', 'Lowndes'): 129,945
('Alabama', 'Macon'): 90,613
('Alabama', 'Madison'): 1,447,168
('Alabama', 'Marengo'): 150,947
('Alabama', 'Marion'): 169,976
('Alabama', 'Marshall'): 772,463
('Alabama', 'Mobile'): 2,483,388
('Alabama', 'Monroe'): 105,141
('Alabama', 'Montgomery'): 1,651,684
('Alabama', 'Morgan'): 684,647
('Alabama', 'Perry'): 94,238
('Alabama', 'Pickens'): 132,191
('Alabama', 'Pike'): 206,301
('Alabama', 'Randolph'): 122,770
('Alabama', 'Russell'): 302,436
('Alabama', 'Shelby'): 1,102,647
('Alabama', 'St. Clair'): 438,368
('Alabama', 'Sumter'): 89,681
('Alabama', 'Talladega'): 381,325
('Alabama', 'Tallapoosa'): 240,501
('Alabama', 'Tuscaloosa'): 1,453,811
('Alabama', 'Walker'): 441,008
('Alabama', 'Washington'): 105,525
('Alabama', 'Wilcox'): 100,637
('Alabama', 'Winston'): 142,834
('Alaska', 'Aleutians East Borough'): 2,410
('Alaska', 'Aleutians West Census Area'): 15,712
('Alaska', 'Anchorage'): 1,181,924
('Alaska', 'Bethel Census Area'): 76,219
('Alaska', 'Bristol Bay Borough'): 12,262
('Alaska', 'Denali Borough'): 3,120
('Alaska', 'Dillingham Census Area'): 8,065
('Alaska', 'Fairbanks North Star Borough'): 278,834
('Alaska', 'Haines Borough'): 1,984
('Alaska', 'Juneau City and Borough'): 74,121
('Alaska', 'Kenai Peninsula Borough'): 182,596
('Alaska', 'Ketchikan Gateway Borough'): 17,574
('Alaska', 'Kodiak Island Borough'): 23,130
('Alaska', 'Kusilvak Census Area'): 23,922
('Alaska', 'Lake and Peninsula Borough'): 883
('Alaska', 'Matanuska-Susitna Borough'): 230,978
('Alaska', 'Nome Census Area'): 16,767
('Alaska', 'North Slope Borough'): 32,513
('Alaska', 'Northwest Arctic Borough'): 27,147
('Alaska', 'Petersburg Borough'): 2,566
('Alaska', 'Prince of Wales-Hyder Census Area'): 5,011
('Alaska', 'Sitka City and Borough'): 14,427
('Alaska', 'Skagway Municipality'): 553
('Alaska', 'Southeast Fairbanks Census Area'): 16,341
('Alaska', 'Unknown'): 19,477
('Alaska', 'Valdez-Cordova Census Area'): 25,506
('Alaska', 'Wrangell City and Borough'): 2,900
('Alaska', 'Yukon-Koyukuk Census Area'): 15,835
('Arizona', 'Apache'): 749,274
('Arizona', 'Cochise'): 395,916
('Arizona', 'Coconino'): 867,702
('Arizona', 'Gila'): 277,956
('Arizona', 'Graham'): 182,683
('Arizona', 'Greenlee'): 17,744
('Arizona', 'La Paz'): 110,866
('Arizona', 'Maricopa'): 26,528,886
('Arizona', 'Mohave'): 750,723
('Arizona', 'Navajo'): 1,194,600
('Arizona', 'Pima'): 4,668,383
('Arizona', 'Pinal'): 2,009,294
('Arizona', 'Santa Cruz'): 556,480
('Arizona', 'Unknown'): 13
('Arizona', 'Yavapai'): 546,670
('Arizona', 'Yuma'): 2,416,265
('Arkansas', 'Arkansas'): 85,085
('Arkansas', 'Ashley'): 84,511
('Arkansas', 'Baxter'): 92,190
('Arkansas', 'Benton'): 1,309,916
('Arkansas', 'Boone'): 137,489
('Arkansas', 'Bradley'): 56,761
('Arkansas', 'Calhoun'): 9,376
('Arkansas', 'Carroll'): 136,612
('Arkansas', 'Chicot'): 154,858
('Arkansas', 'Clark'): 74,503
('Arkansas', 'Clay'): 69,287
('Arkansas', 'Cleburne'): 74,740
('Arkansas', 'Cleveland'): 35,276
('Arkansas', 'Columbia'): 95,328
('Arkansas', 'Conway'): 58,626
('Arkansas', 'Craighead'): 615,166
('Arkansas', 'Crawford'): 273,410
('Arkansas', 'Crittenden'): 379,897
('Arkansas', 'Cross'): 82,586
('Arkansas', 'Dallas'): 27,340
('Arkansas', 'Desha'): 58,448
('Arkansas', 'Drew'): 71,438
('Arkansas', 'Faulkner'): 471,065
('Arkansas', 'Franklin'): 63,907
('Arkansas', 'Fulton'): 39,308
('Arkansas', 'Garland'): 361,918
('Arkansas', 'Grant'): 53,763
('Arkansas', 'Greene'): 222,130
('Arkansas', 'Hempstead'): 79,690
('Arkansas', 'Hot Spring'): 346,075
('Arkansas', 'Howard'): 88,144
('Arkansas', 'Independence'): 192,980
('Arkansas', 'Izard'): 68,185
('Arkansas', 'Jackson'): 114,325
('Arkansas', 'Jefferson'): 567,128
('Arkansas', 'Johnson'): 155,392
('Arkansas', 'Lafayette'): 23,289
('Arkansas', 'Lawrence'): 103,002
('Arkansas', 'Lee'): 190,841
('Arkansas', 'Lincoln'): 386,310
('Arkansas', 'Little River'): 62,298
('Arkansas', 'Logan'): 85,093
('Arkansas', 'Lonoke'): 234,681
('Arkansas', 'Madison'): 72,133
('Arkansas', 'Marion'): 26,517
('Arkansas', 'Miller'): 189,763
('Arkansas', 'Mississippi'): 314,613
('Arkansas', 'Monroe'): 27,587
('Arkansas', 'Montgomery'): 25,422
('Arkansas', 'Nevada'): 45,829
('Arkansas', 'Newton'): 39,517
('Arkansas', 'Ouachita'): 57,535
('Arkansas', 'Perry'): 21,804
('Arkansas', 'Phillips'): 98,308
('Arkansas', 'Pike'): 38,152
('Arkansas', 'Poinsett'): 140,806
('Arkansas', 'Polk'): 63,975
('Arkansas', 'Pope'): 395,211
('Arkansas', 'Prairie'): 31,635
('Arkansas', 'Pulaski'): 1,750,827
('Arkansas', 'Randolph'): 88,321
('Arkansas', 'Saline'): 427,797
('Arkansas', 'Scott'): 28,325
('Arkansas', 'Searcy'): 26,795
('Arkansas', 'Sebastian'): 681,401
('Arkansas', 'Sevier'): 231,807
('Arkansas', 'Sharp'): 55,559
('Arkansas', 'St. Francis'): 298,961
('Arkansas', 'Stone'): 49,488
('Arkansas', 'Union'): 168,478
('Arkansas', 'Unknown'): 325,561
('Arkansas', 'Van Buren'): 35,122
('Arkansas', 'Washington'): 1,741,291
('Arkansas', 'White'): 216,179
('Arkansas', 'Woodruff'): 15,000
('Arkansas', 'Yell'): 229,936
('California', 'Alameda'): 3,747,518
('California', 'Alpine'): 2,054
('California', 'Amador'): 60,647
('California', 'Butte'): 434,503
('California', 'Calaveras'): 53,586
('California', 'Colusa'): 86,109
('California', 'Contra Costa'): 2,840,583
('California', 'Del Norte'): 33,178
('California', 'El Dorado'): 233,360
('California', 'Fresno'): 4,664,002
('California', 'Glenn'): 99,344
('California', 'Humboldt'): 96,673
('California', 'Imperial'): 2,228,174
('California', 'Inyo'): 32,996
('California', 'Kern'): 5,279,000
('California', 'Kings'): 1,336,607
('California', 'Lake'): 92,711
('California', 'Lassen'): 174,696
('California', 'Los Angeles'): 51,616,858
('California', 'Madera'): 724,222
('California', 'Marin'): 1,130,273
('California', 'Mariposa'): 15,006
('California', 'Mendocino'): 158,655
('California', 'Merced'): 1,434,079
('California', 'Modoc'): 6,521
('California', 'Mono'): 45,058
('California', 'Monterey'): 1,692,777
('California', 'Napa'): 321,163
('California', 'Nevada'): 118,187
('California', 'Orange'): 9,970,193
('California', 'Placer'): 688,500
('California', 'Plumas'): 13,987
('California', 'Riverside'): 10,972,598
('California', 'Sacramento'): 3,943,014
('California', 'San Benito'): 221,568
('California', 'San Bernardino'): 10,304,685
('California', 'San Diego'): 9,135,438
('California', 'San Francisco'): 2,026,508
('California', 'San Joaquin'): 3,322,152
('California', 'San Luis Obispo'): 652,338
('California', 'San Mateo'): 1,818,242
('California', 'Santa Barbara'): 1,609,919
('California', 'Santa Clara'): 3,909,770
('California', 'Santa Cruz'): 443,333
('California', 'Shasta'): 316,178
('California', 'Sierra'): 1,260
('California', 'Siskiyou'): 45,788
('California', 'Solano'): 1,168,097
('California', 'Sonoma'): 1,314,785
('California', 'Stanislaus'): 2,784,383
('California', 'Sutter'): 318,512
('California', 'Tehama'): 130,926
('California', 'Trinity'): 7,799
('California', 'Tulare'): 2,751,084
('California', 'Tuolumne'): 69,608
('California', 'Unknown'): 7
('California', 'Ventura'): 2,294,858
('California', 'Yolo'): 515,767
('California', 'Yuba'): 206,803
('Colorado', 'Adams'): 2,520,090
('Colorado', 'Alamosa'): 63,288
('Colorado', 'Arapahoe'): 2,549,241
('Colorado', 'Archuleta'): 16,383
('Colorado', 'Baca'): 7,536
('Colorado', 'Bent'): 13,080
('Colorado', 'Boulder'): 939,815
('Colorado', 'Broomfield'): 176,880
('Colorado', 'Chaffee'): 71,732
('Colorado', 'Cheyenne'): 4,007
('Colorado', 'Clear Creek'): 14,375
('Colorado', 'Conejos'): 12,431
('Colorado', 'Costilla'): 8,023
('Colorado', 'Crowley'): 57,908
('Colorado', 'Custer'): 5,380
('Colorado', 'Delta'): 52,639
('Colorado', 'Denver'): 3,464,656
('Colorado', 'Dolores'): 1,147
('Colorado', 'Douglas'): 802,954
('Colorado', 'Eagle'): 300,416
('Colorado', 'El Paso'): 2,072,301
('Colorado', 'Elbert'): 45,933
('Colorado', 'Fremont'): 143,243
('Colorado', 'Garfield'): 213,874
('Colorado', 'Gilpin'): 6,090
('Colorado', 'Grand'): 26,279
('Colorado', 'Gunnison'): 70,182
('Colorado', 'Hinsdale'): 1,008
('Colorado', 'Huerfano'): 8,783
('Colorado', 'Jackson'): 1,884
('Colorado', 'Jefferson'): 1,684,976
('Colorado', 'Kiowa'): 1,356
('Colorado', 'Kit Carson'): 24,397
('Colorado', 'La Plata'): 90,296
('Colorado', 'Lake'): 25,257
('Colorado', 'Larimer'): 749,644
('Colorado', 'Las Animas'): 13,896
('Colorado', 'Lincoln'): 15,408
('Colorado', 'Logan'): 236,156
('Colorado', 'Mesa'): 314,596
('Colorado', 'Mineral'): 3,919
('Colorado', 'Moffat'): 17,390
('Colorado', 'Montezuma'): 49,373
('Colorado', 'Montrose'): 102,249
('Colorado', 'Morgan'): 202,021
('Colorado', 'Otero'): 42,672
('Colorado', 'Ouray'): 8,245
('Colorado', 'Park'): 18,266
('Colorado', 'Phillips'): 11,779
('Colorado', 'Pitkin'): 53,790
('Colorado', 'Prowers'): 37,496
('Colorado', 'Pueblo'): 493,284
('Colorado', 'Rio Blanco'): 8,431
('Colorado', 'Rio Grande'): 24,586
('Colorado', 'Routt'): 49,939
('Colorado', 'Saguache'): 27,328
('Colorado', 'San Juan'): 1,495
('Colorado', 'San Miguel'): 22,166
('Colorado', 'Sedgwick'): 6,225
('Colorado', 'Summit'): 133,476
('Colorado', 'Teller'): 48,352
('Colorado', 'Unknown'): 6,823
('Colorado', 'Washington'): 19,530
('Colorado', 'Weld'): 1,317,580
('Colorado', 'Yuma'): 29,600
('Connecticut', 'Fairfield'): 5,278,812
('Connecticut', 'Hartford'): 3,739,924
('Connecticut', 'Litchfield'): 515,960
('Connecticut', 'Middlesex'): 432,998
('Connecticut', 'New Haven'): 3,880,490
('Connecticut', 'New London'): 592,491
('Connecticut', 'Tolland'): 344,058
('Connecticut', 'Unknown'): 78,873
('Connecticut', 'Windham'): 257,291
('Delaware', 'Kent'): 664,082
('Delaware', 'New Castle'): 2,264,108
('Delaware', 'Sussex'): 1,542,964
('Delaware', 'Unknown'): 35,766
('District of Columbia', 'District of Columbia'): 3,311,752
('Florida', 'Alachua'): 1,358,137
('Florida', 'Baker'): 227,762
('Florida', 'Bay'): 992,894
('Florida', 'Bradford'): 161,161
('Florida', 'Brevard'): 1,660,660
('Florida', 'Broward'): 13,601,047
('Florida', 'Calhoun'): 104,746
('Florida', 'Charlotte'): 577,992
('Florida', 'Citrus'): 476,472
('Florida', 'Clay'): 885,914
('Florida', 'Collier'): 2,319,305
('Florida', 'Columbia'): 604,707
('Florida', 'DeSoto'): 292,021
('Florida', 'Dixie'): 122,278
('Florida', 'Duval'): 5,330,150
('Florida', 'Escambia'): 2,085,676
('Florida', 'Flagler'): 304,266
('Florida', 'Franklin'): 94,444
('Florida', 'Gadsden'): 434,655
('Florida', 'Gilchrist'): 88,847
('Florida', 'Glades'): 90,412
('Florida', 'Gulf'): 131,906
('Florida', 'Hamilton'): 145,504
('Florida', 'Hardee'): 229,718
('Florida', 'Hendry'): 375,506
('Florida', 'Hernando'): 543,805
('Florida', 'Highlands'): 393,743
('Florida', 'Hillsborough'): 7,335,664
('Florida', 'Holmes'): 130,842
('Florida', 'Indian River'): 578,426
('Florida', 'Jackson'): 457,905
('Florida', 'Jefferson'): 92,672
('Florida', 'Lafayette'): 165,259
('Florida', 'Lake'): 1,276,082
('Florida', 'Lee'): 3,742,621
('Florida', 'Leon'): 1,632,204
('Florida', 'Levy'): 169,156
('Florida', 'Liberty'): 93,208
('Florida', 'Madison'): 164,726
('Florida', 'Manatee'): 2,082,482
('Florida', 'Marion'): 1,538,381
('Florida', 'Martin'): 867,977
('Florida', 'Miami-Dade'): 29,606,258
('Florida', 'Monroe'): 354,577
('Florida', 'Nassau'): 350,709
('Florida', 'Okaloosa'): 926,634
('Florida', 'Okeechobee'): 251,912
('Florida', 'Orange'): 7,121,528
('Florida', 'Osceola'): 2,189,335
('Florida', 'Palm Beach'): 8,375,411
('Florida', 'Pasco'): 1,684,250
('Florida', 'Pinellas'): 4,037,742
('Florida', 'Polk'): 3,387,229
('Florida', 'Putnam'): 353,537
('Florida', 'Santa Rosa'): 891,663
('Florida', 'Sarasota'): 1,511,211
('Florida', 'Seminole'): 1,617,474
('Florida', 'St. Johns'): 963,245
('Florida', 'St. Lucie'): 1,355,293
('Florida', 'Sumter'): 405,909
('Florida', 'Suwannee'): 427,699
('Florida', 'Taylor'): 200,090
('Florida', 'Union'): 137,102
('Florida', 'Unknown'): 262,055
('Florida', 'Volusia'): 1,913,394
('Florida', 'Wakulla'): 181,457
('Florida', 'Walton'): 372,022
('Florida', 'Washington'): 179,073
('Georgia', 'Appling'): 177,957
('Georgia', 'Atkinson'): 79,299
('Georgia', 'Bacon'): 107,763
('Georgia', 'Baker'): 17,483
('Georgia', 'Baldwin'): 343,855
('Georgia', 'Banks'): 88,095
('Georgia', 'Barrow'): 397,530
('Georgia', 'Bartow'): 575,680
('Georgia', 'Ben Hill'): 129,605
('Georgia', 'Berrien'): 84,462
('Georgia', 'Bibb'): 977,900
('Georgia', 'Bleckley'): 78,771
('Georgia', 'Brantley'): 81,882
('Georgia', 'Brooks'): 93,681
('Georgia', 'Bryan'): 181,409
('Georgia', 'Bulloch'): 436,888
('Georgia', 'Burke'): 146,736
('Georgia', 'Butts'): 138,654
('Georgia', 'Calhoun'): 52,517
('Georgia', 'Camden'): 209,013
('Georgia', 'Candler'): 72,052
('Georgia', 'Carroll'): 596,727
('Georgia', 'Catoosa'): 218,732
('Georgia', 'Charlton'): 101,352
('Georgia', 'Chatham'): 1,373,409
('Georgia', 'Chattahoochee'): 247,781
('Georgia', 'Chattooga'): 125,949
('Georgia', 'Cherokee'): 1,144,516
('Georgia', 'Clarke'): 839,577
('Georgia', 'Clay'): 22,629
('Georgia', 'Clayton'): 1,330,749
('Georgia', 'Clinch'): 64,866
('Georgia', 'Cobb'): 3,633,457
('Georgia', 'Coffee'): 375,160
('Georgia', 'Colquitt'): 378,400
('Georgia', 'Columbia'): 692,102
('Georgia', 'Cook'): 103,891
('Georgia', 'Coweta'): 552,609
('Georgia', 'Crawford'): 31,182
('Georgia', 'Crisp'): 125,028
('Georgia', 'Dade'): 52,947
('Georgia', 'Dawson'): 135,917
('Georgia', 'DeKalb'): 3,526,275
('Georgia', 'Decatur'): 201,444
('Georgia', 'Dodge'): 102,788
('Georgia', 'Dooly'): 73,523
('Georgia', 'Dougherty'): 683,510
('Georgia', 'Douglas'): 684,834
('Georgia', 'Early'): 104,538
('Georgia', 'Echols'): 48,190
('Georgia', 'Effingham'): 240,056
('Georgia', 'Elbert'): 121,098
('Georgia', 'Emanuel'): 163,246
('Georgia', 'Evans'): 66,754
('Georgia', 'Fannin'): 111,728
('Georgia', 'Fayette'): 354,897
('Georgia', 'Floyd'): 568,694
('Georgia', 'Forsyth'): 745,141
('Georgia', 'Franklin'): 135,246
('Georgia', 'Fulton'): 5,136,007
('Georgia', 'Gilmer'): 158,021
('Georgia', 'Glascock'): 8,286
('Georgia', 'Glynn'): 570,559
('Georgia', 'Gordon'): 359,840
('Georgia', 'Grady'): 132,225
('Georgia', 'Greene'): 90,062
('Georgia', 'Gwinnett'): 5,017,795
('Georgia', 'Habersham'): 313,173
('Georgia', 'Hall'): 1,705,910
('Georgia', 'Hancock'): 76,719
('Georgia', 'Haralson'): 111,156
('Georgia', 'Harris'): 145,514
('Georgia', 'Hart'): 90,575
('Georgia', 'Heard'): 41,656
('Georgia', 'Henry'): 1,001,152
('Georgia', 'Houston'): 570,499
('Georgia', 'Irwin'): 52,282
('Georgia', 'Jackson'): 361,637
('Georgia', 'Jasper'): 51,236
('Georgia', 'Jeff Davis'): 119,920
('Georgia', 'Jefferson'): 126,315
('Georgia', 'Jenkins'): 66,013
('Georgia', 'Johnson'): 70,680
('Georgia', 'Jones'): 93,140
('Georgia', 'Lamar'): 77,773
('Georgia', 'Lanier'): 54,266
('Georgia', 'Laurens'): 293,932
('Georgia', 'Lee'): 154,622
('Georgia', 'Liberty'): 183,559
('Georgia', 'Lincoln'): 37,784
('Georgia', 'Long'): 39,813
('Georgia', 'Lowndes'): 762,931
('Georgia', 'Lumpkin'): 146,469
('Georgia', 'Macon'): 49,049
('Georgia', 'Madison'): 124,586
('Georgia', 'Marion'): 36,449
('Georgia', 'McDuffie'): 108,087
('Georgia', 'McIntosh'): 47,011
('Georgia', 'Meriwether'): 103,491
('Georgia', 'Miller'): 47,429
('Georgia', 'Mitchell'): 165,323
('Georgia', 'Monroe'): 127,408
('Georgia', 'Montgomery'): 49,176
('Georgia', 'Morgan'): 89,195
('Georgia', 'Murray'): 175,739
('Georgia', 'Muscogee'): 1,032,044
('Georgia', 'Newton'): 476,696
('Georgia', 'Oconee'): 150,605
('Georgia', 'Oglethorpe'): 65,649
('Georgia', 'Paulding'): 542,893
('Georgia', 'Peach'): 120,808
('Georgia', 'Pickens'): 116,773
('Georgia', 'Pierce'): 135,762
('Georgia', 'Pike'): 80,213
('Georgia', 'Polk'): 259,865
('Georgia', 'Pulaski'): 51,394
('Georgia', 'Putnam'): 122,565
('Georgia', 'Quitman'): 8,557
('Georgia', 'Rabun'): 63,567
('Georgia', 'Randolph'): 68,579
('Georgia', 'Richmond'): 1,209,398
('Georgia', 'Rockdale'): 343,999
('Georgia', 'Schley'): 20,328
('Georgia', 'Screven'): 63,519
('Georgia', 'Seminole'): 59,998
('Georgia', 'Spalding'): 277,809
('Georgia', 'Stephens'): 184,225
('Georgia', 'Stewart'): 80,782
('Georgia', 'Sumter'): 203,959
('Georgia', 'Talbot'): 32,399
('Georgia', 'Taliaferro'): 3,977
('Georgia', 'Tattnall'): 134,932
('Georgia', 'Taylor'): 38,479
('Georgia', 'Telfair'): 77,138
('Georgia', 'Terrell'): 75,649
('Georgia', 'Thomas'): 272,440
('Georgia', 'Tift'): 332,092
('Georgia', 'Toombs'): 210,615
('Georgia', 'Towns'): 57,858
('Georgia', 'Treutlen'): 42,910
('Georgia', 'Troup'): 538,981
('Georgia', 'Turner'): 64,849
('Georgia', 'Twiggs'): 31,726
('Georgia', 'Union'): 115,597
('Georgia', 'Unknown'): 515,629
('Georgia', 'Upson'): 184,178
('Georgia', 'Walker'): 270,720
('Georgia', 'Walton'): 359,225
('Georgia', 'Ware'): 313,708
('Georgia', 'Warren'): 25,299
('Georgia', 'Washington'): 126,218
('Georgia', 'Wayne'): 188,024
('Georgia', 'Webster'): 8,994
('Georgia', 'Wheeler'): 47,616
('Georgia', 'White'): 140,375
('Georgia', 'Whitfield'): 868,803
('Georgia', 'Wilcox'): 53,173
('Georgia', 'Wilkes'): 50,451
('Georgia', 'Wilkinson'): 58,073
('Georgia', 'Worth'): 114,810
('Guam', 'Unknown'): 770,612
('Hawaii', 'Hawaii'): 141,771
('Hawaii', 'Honolulu'): 1,631,458
('Hawaii', 'Kalawao'): 10
('Hawaii', 'Kauai'): 13,567
('Hawaii', 'Maui'): 92,028
('Hawaii', 'Unknown'): 202
('Idaho', 'Ada'): 2,584,383
('Idaho', 'Adams'): 8,582
('Idaho', 'Bannock'): 322,280
('Idaho', 'Bear Lake'): 12,469
('Idaho', 'Benewah'): 26,153
('Idaho', 'Bingham'): 208,573
('Idaho', 'Blaine'): 184,980
('Idaho', 'Boise'): 13,523
('Idaho', 'Bonner'): 78,424
('Idaho', 'Bonneville'): 596,964
('Idaho', 'Boundary'): 23,075
('Idaho', 'Butte'): 9,392
('Idaho', 'Camas'): 4,392
('Idaho', 'Canyon'): 1,538,821
('Idaho', 'Caribou'): 31,316
('Idaho', 'Cassia'): 185,454
('Idaho', 'Clark'): 4,786
('Idaho', 'Clearwater'): 27,749
('Idaho', 'Custer'): 11,960
('Idaho', 'Elmore'): 80,141
('Idaho', 'Franklin'): 46,036
('Idaho', 'Fremont'): 53,465
('Idaho', 'Gem'): 72,075
('Idaho', 'Gooding'): 77,593
('Idaho', 'Idaho'): 48,025
('Idaho', 'Jefferson'): 122,587
('Idaho', 'Jerome'): 174,316
('Idaho', 'Kootenai'): 633,563
('Idaho', 'Latah'): 117,935
('Idaho', 'Lemhi'): 29,340
('Idaho', 'Lewis'): 12,052
('Idaho', 'Lincoln'): 29,143
('Idaho', 'Madison'): 276,825
('Idaho', 'Minidoka'): 159,171
('Idaho', 'Nez Perce'): 147,372
('Idaho', 'Oneida'): 9,536
('Idaho', 'Owyhee'): 64,650
('Idaho', 'Payette'): 155,459
('Idaho', 'Power'): 43,285
('Idaho', 'Shoshone'): 42,715
('Idaho', 'Teton'): 42,453
('Idaho', 'Twin Falls'): 573,949
('Idaho', 'Unknown'): 1,219
('Idaho', 'Valley'): 21,213
('Idaho', 'Washington'): 71,720
('Illinois', 'Adams'): 320,033
('Illinois', 'Alexander'): 19,975
('Illinois', 'Bond'): 73,517
('Illinois', 'Boone'): 324,303
('Illinois', 'Brown'): 19,184
('Illinois', 'Bureau'): 146,741

In [18]:
# no need to use 'for' cycles, just indicate the necessary agregation field after:
data_df.groupby(['state', 'county'])['cases'].sum()

state    county
Alabama  Autauga     322927
         Baldwin     975405
         Barbour     157947
         Bibb        127509
         Blount      296336
                      ...
Wyoming  Teton       134109
         Uinta        87556
         Unknown         37
         Washakie     32372
         Weston       21695
Name: cases, Length: 3273, dtype: int64

In [19]:
# executing multiple math methods in agregations with .agg() method
data_df.groupby(['state', 'county']).agg({'cases': ['sum', 'max', 'min', 'mean']})

                   cases
                     sum    max min         mean
state   county
Alabama Autauga   322927   3698   1  1191.612546
        Baldwin   975405  11722   1  3471.192171
        Barbour   157947   1330   1   605.160920
        Bibb      127509   1601   2   481.166038
        Blount    296336   4191   1  1097.540741
...                  ...    ...  ..          ...
Wyoming Teton     134109   1992   1   484.148014
        Uinta      87556   1406   1   334.183206
        Unknown       37     30   1     9.250000
        Washakie   32372    694   1   120.791045
        Weston     21695    443   1   104.806763

[3273 rows x 4 columns]

In [20]:
# as .agg() returns a DF, not just Series, we can add more fields for agregation:
data_df.groupby(['state', 'county']).agg({'cases': ['sum', 'max', 'min', 'mean'],
                                          'fips': ['sum']})

                   cases                                fips
                     sum    max min         mean         sum
state   county
Alabama Autauga   322927   3698   1  1191.612546    271271.0
        Baldwin   975405  11722   1  3471.192171    281843.0
        Barbour   157947   1330   1   605.160920    262305.0
        Bibb      127509   1601   2   481.166038    266855.0
        Blount    296336   4191   1  1097.540741    272430.0
...                  ...    ...  ..          ...         ...
Wyoming Teton     134109   1992   1   484.148014  15522803.0
        Uinta      87556   1406   1   334.183206  14682742.0
        Unknown       37     30   1     9.250000         0.0
        Washakie   32372    694   1   120.791045  15019524.0
        Weston     21695    443   1   104.806763  11601315.0

[3273 rows x 5 columns]

In [22]:
# index will be a combination of state and county:
data_agg = data_df.groupby(['state', 'county']).agg({'cases': ['sum', 'max', 'min', 'mean'],
                                          'fips': ['sum']})
data_agg.index

MultiIndex([('Alabama',    'Autauga'),
            ('Alabama',    'Baldwin'),
            ('Alabama',    'Barbour'),
            ('Alabama',       'Bibb'),
            ('Alabama',     'Blount'),
            ('Alabama',    'Bullock'),
            ('Alabama',     'Butler'),
            ('Alabama',    'Calhoun'),
            ('Alabama',   'Chambers'),
            ('Alabama',   'Cherokee'),
            ...
            ('Wyoming',       'Park'),
            ('Wyoming',     'Platte'),
            ('Wyoming',   'Sheridan'),
            ('Wyoming',   'Sublette'),
            ('Wyoming', 'Sweetwater'),
            ('Wyoming',      'Teton'),
            ('Wyoming',      'Uinta'),
            ('Wyoming',    'Unknown'),
            ('Wyoming',   'Washakie'),
            ('Wyoming',     'Weston')],
           names=['state', 'county'], length=3273)

In [24]:
# we can reset index to have a default digit-based index, basically moving our composite index into DF:
data_agg.reset_index()

        state    county   cases                                fips
                            sum    max min         mean         sum
0     Alabama   Autauga  322927   3698   1  1191.612546    271271.0
1     Alabama   Baldwin  975405  11722   1  3471.192171    281843.0
2     Alabama   Barbour  157947   1330   1   605.160920    262305.0
3     Alabama      Bibb  127509   1601   2   481.166038    266855.0
4     Alabama    Blount  296336   4191   1  1097.540741    272430.0
...       ...       ...     ...    ...  ..          ...         ...
3268  Wyoming     Teton  134109   1992   1   484.148014  15522803.0
3269  Wyoming     Uinta   87556   1406   1   334.183206  14682742.0
3270  Wyoming   Unknown      37     30   1     9.250000         0.0
3271  Wyoming  Washakie   32372    694   1   120.791045  15019524.0
3272  Wyoming    Weston   21695    443   1   104.806763  11601315.0

[3273 rows x 7 columns]

In [25]:
# we can create our own agregation funcs, using anonymous lambda (can be also used for formatting):
data_df.groupby(['state', 'county']).agg({'cases': ['mean', lambda values: (values>0).sum()]})

                        cases
                         mean <lambda_0>
state   county
Alabama Autauga   1191.612546        271
        Baldwin   3471.192171        281
        Barbour    605.160920        261
        Bibb       481.166038        265
        Blount    1097.540741        270
...                       ...        ...
Wyoming Teton      484.148014        277
        Uinta      334.183206        262
        Unknown      9.250000          4
        Washakie   120.791045        268
        Weston     104.806763        207

[3273 rows x 2 columns]

In [27]:
# (can be also used for formatting)
data_df.groupby(['state', 'county']).agg({'cases': ['mean', lambda values: '$ '+ str((values>0).sum())]})

                        cases
                         mean <lambda_0>
state   county
Alabama Autauga   1191.612546      $ 271
        Baldwin   3471.192171      $ 281
        Barbour    605.160920      $ 261
        Bibb       481.166038      $ 265
        Blount    1097.540741      $ 270
...                       ...        ...
Wyoming Teton      484.148014      $ 277
        Uinta      334.183206      $ 262
        Unknown      9.250000        $ 4
        Washakie   120.791045      $ 268
        Weston     104.806763      $ 207

[3273 rows x 2 columns]

#### - stack & unstack

In [29]:
data_agg = data_df.groupby(['state', 'county']).agg({'cases': ['sum', 'max', 'min', 'mean'],
                                          'fips': ['sum']})
data_agg

                   cases                                fips
                     sum    max min         mean         sum
state   county
Alabama Autauga   322927   3698   1  1191.612546    271271.0
        Baldwin   975405  11722   1  3471.192171    281843.0
        Barbour   157947   1330   1   605.160920    262305.0
        Bibb      127509   1601   2   481.166038    266855.0
        Blount    296336   4191   1  1097.540741    272430.0
...                  ...    ...  ..          ...         ...
Wyoming Teton     134109   1992   1   484.148014  15522803.0
        Uinta      87556   1406   1   334.183206  14682742.0
        Unknown       37     30   1     9.250000         0.0
        Washakie   32372    694   1   120.791045  15019524.0
        Weston     21695    443   1   104.806763  11601315.0

[3273 rows x 5 columns]

In [32]:
# last index get converted into column
data_agg.unstack(fill_value=0)

                             cases                                             \
                               sum
county                   Abbeville  Acadia Accomack      Ada   Adair    Adams
state
Alabama                          0       0        0        0       0        0
Alaska                           0       0        0        0       0        0
Arizona                          0       0        0        0       0        0
Arkansas                         0       0        0        0       0        0
California                       0       0        0        0       0        0
Colorado                         0       0        0        0       0  2520090
Connecticut                      0       0        0        0       0        0
Delaware                         0       0        0        0       0        0
District of Columbia             0       0        0        0       0        0
Florida                          0       0        0        0       0        0
Georgia                          0       0        0        0       0        0
Guam                             0       0        0        0       0        0
Hawaii                           0       0        0        0       0        0
Idaho                            0       0        0  2584383       0     8582
Illinois                         0       0        0        0       0   320033
Indiana                          0       0        0        0       0   107278
Iowa                             0       0        0        0   27741    11705
Kansas                           0       0        0        0       0        0
Kentucky                         0       0        0        0   87609        0
Louisiana                        0  532901        0        0       0        0
Maine                            0       0        0        0       0        0
Maryland                         0       0        0        0       0        0
Massachusetts                    0       0        0        0       0        0
Michigan                         0       0        0        0       0        0
Minnesota                        0       0        0        0       0        0
Mississippi                      0       0        0        0       0   173462
Missouri                         0       0        0        0   90317        0
Montana                          0       0        0        0       0        0
Nebraska                         0       0        0        0       0   152309
Nevada                           0       0        0        0       0        0
New Hampshire                    0       0        0        0       0        0
New Jersey                       0       0        0        0       0        0
New Mexico                       0       0        0        0       0        0
New York                         0       0        0        0       0        0
North Carolina                   0       0        0        0       0        0
North Dakota                     0       0        0        0       0     9719
Northern Mariana Islands         0       0        0        0       0        0
Ohio                             0       0        0        0       0    49349
Oklahoma                         0       0        0        0  120710        0
Oregon                           0       0        0        0       0        0
Pennsylvania                     0       0        0        0       0   198647
Puerto Rico                      0       0        0        0       0        0
Rhode Island                     0       0        0        0       0        0
South Carolina              104512       0        0        0       0        0
South Dakota                     0       0        0        0       0        0
Tennessee                        0       0        0        0       0        0
Texas                            0       0        0        0       0        0
Utah                             0       0        0        0       0        0
Vermont                          0       0        0        0       0        0
Virgin Islands                   0       0        0        0       0        0
Virginia                         0       0   256007        0       0        0
Washington                       0       0        0        0       0   141452
West Virginia                    0       0        0        0       0        0
Wisconsin                        0       0        0        0       0    73754
Wyoming                          0       0        0        0       0        0

                                                            ...        fips  \
                                                            ...         sum
county                   Addison Adjuntas Aguada Aguadilla  ...      Yoakum
state                                                       ...
Alabama                        0        0      0         0  ...         0.0
Alaska                         0        0      0         0  ...         0.0
Arizona                        0        0      0         0  ...         0.0
Arkansas                       0        0      0         0  ...         0.0
California                     0        0      0         0  ...         0.0
Colorado                       0        0      0         0  ...         0.0
Connecticut                    0        0      0         0  ...         0.0
Delaware                       0        0      0         0  ...         0.0
District of Columbia           0        0      0         0  ...         0.0
Florida                        0        0      0         0  ...         0.0
Georgia                        0        0      0         0  ...         0.0
Guam                           0        0      0         0  ...         0.0
Hawaii                         0        0      0         0  ...         0.0
Idaho                          0        0      0         0  ...         0.0
Illinois                       0        0      0         0  ...         0.0
Indiana                        0        0      0         0  ...         0.0
Iowa                           0        0      0         0  ...         0.0
Kansas                         0        0      0         0  ...         0.0
Kentucky                       0        0      0         0  ...         0.0
Louisiana                      0        0      0         0  ...         0.0
Maine                          0        0      0         0  ...         0.0
Maryland                       0        0      0         0  ...         0.0
Massachusetts                  0        0      0         0  ...         0.0
Michigan                       0        0      0         0  ...         0.0
Minnesota                      0        0      0         0  ...         0.0
Mississippi                    0        0      0         0  ...         0.0
Missouri                       0        0      0         0  ...         0.0
Montana                        0        0      0         0  ...         0.0
Nebraska                       0        0      0         0  ...         0.0
Nevada                         0        0      0         0  ...         0.0
New Hampshire                  0        0      0         0  ...         0.0
New Jersey                     0        0      0         0  ...         0.0
New Mexico                     0        0      0         0  ...         0.0
New York                       0        0      0         0  ...         0.0
North Carolina                 0        0      0         0  ...         0.0
North Dakota                   0        0      0         0  ...         0.0
Northern Mariana Islands       0        0      0         0  ...         0.0
Ohio                           0        0      0         0  ...         0.0
Oklahoma                       0        0      0         0  ...         0.0
Oregon                         0        0      0         0  ...         0.0
Pennsylvania                   0        0      0         0  ...         0.0
Puerto Rico                    0    28007  59402     80413  ...         0.0
Rhode Island                   0        0      0         0  ...         0.0
South Carolina                 0        0      0         0  ...         0.0
South Dakota                   0        0      0         0  ...         0.0
Tennessee                      0        0      0         0  ...         0.0
Texas                          0        0      0         0  ...  11931246.0
Utah                           0        0      0         0  ...         0.0
Vermont                    24458        0      0         0  ...         0.0
Virgin Islands                 0        0      0         0  ...         0.0
Virginia                       0        0      0         0  ...         0.0
Washington                     0        0      0         0  ...         0.0
West Virginia                  0        0      0         0  ...         0.0
Wisconsin                      0        0      0         0  ...         0.0
Wyoming                        0        0      0         0  ...         0.0

                                                                        \

county                         Yolo        York       Young       Yuba
state
Alabama                         0.0         0.0         0.0        0.0
Alaska                          0.0         0.0         0.0        0.0
Arizona                         0.0         0.0         0.0        0.0
Arkansas                        0.0         0.0         0.0        0.0
California                1766657.0         0.0         0.0  1675510.0
Colorado                        0.0         0.0         0.0        0.0
Connecticut                     0.0         0.0         0.0        0.0
Delaware                        0.0         0.0         0.0        0.0
District of Columbia            0.0         0.0         0.0        0.0
Florida                         0.0         0.0         0.0        0.0
Georgia                         0.0         0.0         0.0        0.0
Guam                            0.0         0.0         0.0        0.0
Hawaii                          0.0         0.0         0.0        0.0
Idaho                           0.0         0.0         0.0        0.0
Illinois                        0.0         0.0         0.0        0.0
Indiana                         0.0         0.0         0.0        0.0
Iowa                            0.0         0.0         0.0        0.0
Kansas                          0.0         0.0         0.0        0.0
Kentucky                        0.0         0.0         0.0        0.0
Louisiana                       0.0         0.0         0.0        0.0
Maine                           0.0   6402618.0         0.0        0.0
Maryland                        0.0         0.0         0.0        0.0
Massachusetts                   0.0         0.0         0.0        0.0
Michigan                        0.0         0.0         0.0        0.0
Minnesota                       0.0         0.0         0.0        0.0
Mississippi                     0.0         0.0         0.0        0.0
Missouri                        0.0         0.0         0.0        0.0
Montana                         0.0         0.0         0.0        0.0
Nebraska                        0.0   8264025.0         0.0        0.0
Nevada                          0.0         0.0         0.0        0.0
New Hampshire                   0.0         0.0         0.0        0.0
New Jersey                      0.0         0.0         0.0        0.0
New Mexico                      0.0         0.0         0.0        0.0
New York                        0.0         0.0         0.0        0.0
North Carolina                  0.0         0.0         0.0        0.0
North Dakota                    0.0         0.0         0.0        0.0
Northern Mariana Islands        0.0         0.0         0.0        0.0
Ohio                            0.0         0.0         0.0        0.0
Oklahoma                        0.0         0.0         0.0        0.0
Oregon                          0.0         0.0         0.0        0.0
Pennsylvania                    0.0  11670841.0         0.0        0.0
Puerto Rico                     0.0         0.0         0.0        0.0
Rhode Island                    0.0         0.0         0.0        0.0
South Carolina                  0.0  12535298.0         0.0        0.0
South Dakota                    0.0         0.0         0.0        0.0
Tennessee                       0.0         0.0         0.0        0.0
Texas                           0.0         0.0  12998804.0        0.0
Utah                            0.0         0.0         0.0        0.0
Vermont                         0.0         0.0         0.0        0.0
Virgin Islands                  0.0         0.0         0.0        0.0
Virginia                        0.0  14284521.0         0.0        0.0
Washington                      0.0         0.0         0.0        0.0
West Virginia                   0.0         0.0         0.0        0.0
Wisconsin                       0.0         0.0         0.0        0.0
Wyoming                         0.0         0.0         0.0        0.0

                                                                           \

county                   Yukon-Koyukuk Census Area       Yuma      Zapata
state
Alabama                                        0.0        0.0         0.0
Alaska                                    599980.0        0.0         0.0
Arizona                                        0.0  1107425.0         0.0
Arkansas                                       0.0        0.0         0.0
California                                     0.0        0.0         0.0
Colorado                                       0.0  2250625.0         0.0
Connecticut                                    0.0        0.0         0.0
Delaware                                       0.0        0.0         0.0
District of Columbia                           0.0        0.0         0.0
Florida                                        0.0        0.0         0.0
Georgia                                        0.0        0.0         0.0
Guam                                           0.0        0.0         0.0
Hawaii                                         0.0        0.0         0.0
Idaho                                          0.0        0.0         0.0
Illinois                                       0.0        0.0         0.0
Indiana                                        0.0        0.0         0.0
Iowa                                           0.0        0.0         0.0
Kansas                                         0.0        0.0         0.0
Kentucky                                       0.0        0.0         0.0
Louisiana                                      0.0        0.0         0.0
Maine                                          0.0        0.0         0.0
Maryland                                       0.0        0.0         0.0
Massachusetts                                  0.0        0.0         0.0
Michigan                                       0.0        0.0         0.0
Minnesota                                      0.0        0.0         0.0
Mississippi                                    0.0        0.0         0.0
Missouri                                       0.0        0.0         0.0
Montana                                        0.0        0.0         0.0
Nebraska                                       0.0        0.0         0.0
Nevada                                         0.0        0.0         0.0
New Hampshire                                  0.0        0.0         0.0
New Jersey                                     0.0        0.0         0.0
New Mexico                                     0.0        0.0         0.0
New York                                       0.0        0.0         0.0
North Carolina                                 0.0        0.0         0.0
North Dakota                                   0.0        0.0         0.0
Northern Mariana Islands                       0.0        0.0         0.0
Ohio                                           0.0        0.0         0.0
Oklahoma                                       0.0        0.0         0.0
Oregon                                         0.0        0.0         0.0
Pennsylvania                                   0.0        0.0         0.0
Puerto Rico                                    0.0        0.0         0.0
Rhode Island                                   0.0        0.0         0.0
South Carolina                                 0.0        0.0         0.0
South Dakota                                   0.0        0.0         0.0
Tennessee                                      0.0        0.0         0.0
Texas                                          0.0        0.0  12514290.0
Utah                                           0.0        0.0         0.0
Vermont                                        0.0        0.0         0.0
Virgin Islands                                 0.0        0.0         0.0
Virginia                                       0.0        0.0         0.0
Washington                                     0.0        0.0         0.0
West Virginia                                  0.0        0.0         0.0
Wisconsin                                      0.0        0.0         0.0
Wyoming                                        0.0        0.0         0.0



county                        Zavala     Ziebach
state
Alabama                          0.0         0.0
Alaska                           0.0         0.0
Arizona                          0.0         0.0
Arkansas                         0.0         0.0
California                       0.0         0.0
Colorado                         0.0         0.0
Connecticut                      0.0         0.0
Delaware                         0.0         0.0
District of Columbia             0.0         0.0
Florida                          0.0         0.0
Georgia                          0.0         0.0
Guam                             0.0         0.0
Hawaii                           0.0         0.0
Idaho                            0.0         0.0
Illinois                         0.0         0.0
Indiana                          0.0         0.0
Iowa                             0.0         0.0
Kansas                           0.0         0.0
Kentucky                         0.0         0.0
Louisiana                        0.0         0.0
Maine                            0.0         0.0
Maryland                         0.0         0.0
Massachusetts                    0.0         0.0
Michigan                         0.0         0.0
Minnesota                        0.0         0.0
Mississippi                      0.0         0.0
Missouri                         0.0         0.0
Montana                          0.0         0.0
Nebraska                         0.0         0.0
Nevada                           0.0         0.0
New Hampshire                    0.0         0.0
New Jersey                       0.0         0.0
New Mexico                       0.0         0.0
New York                         0.0         0.0
North Carolina                   0.0         0.0
North Dakota                     0.0         0.0
Northern Mariana Islands         0.0         0.0
Ohio                             0.0         0.0
Oklahoma                         0.0         0.0
Oregon                           0.0         0.0
Pennsylvania                     0.0         0.0
Puerto Rico                      0.0         0.0
Rhode Island                     0.0         0.0
South Carolina                   0.0         0.0
South Dakota                     0.0  10519236.0
Tennessee                        0.0         0.0
Texas                     11981229.0         0.0
Utah                             0.0         0.0
Vermont                          0.0         0.0
Virgin Islands                   0.0         0.0
Virginia                         0.0         0.0
Washington                       0.0         0.0
West Virginia                    0.0         0.0
Wisconsin                        0.0         0.0

In [35]:
# moving columns into index:
data_agg.stack()

/var/folders/4s/q7yddbmx5x5cv8bjf0127cvr0000gn/T/ipykernel_55411/52259764.py:2: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  data_agg.stack()

                               cases        fips
state   county
Alabama Autauga  max     3698.000000         NaN
                 mean    1191.612546         NaN
                 min        1.000000         NaN
                 sum   322927.000000    271271.0
        Baldwin  max    11722.000000         NaN
...                              ...         ...
Wyoming Washakie sum    32372.000000  15019524.0
        Weston   max      443.000000         NaN
                 mean     104.806763         NaN
                 min        1.000000         NaN
                 sum    21695.000000  11601315.0

[13092 rows x 2 columns]

#### - rolling, shift, sample

In [37]:
weather = pd.DataFrame({'date': ['5/1/2017', '5/2/2017', '5/3/2017', '5/4/2017', '5/5/2017', '5/6/2017', '5/7/2017', '5/8/2017', '5/9/2017'],                        
                        'temperature': [34, 54, 43, 54, 30, 54, 52, 46, 40],
                        'cloudy': [1, 2, 3, 4, 5, 6, 7, 8, 9],
                        'snowing': ['Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No']})
weather

       date  temperature  cloudy snowing
0  5/1/2017           34       1     Yes
1  5/2/2017           54       2     Yes
2  5/3/2017           43       3     Yes
3  5/4/2017           54       4     Yes
4  5/5/2017           30       5     Yes
5  5/6/2017           54       6      No
6  5/7/2017           52       7      No
7  5/8/2017           46       8      No
8  5/9/2017           40       9      No

In [38]:
# using .rolling() to calculate mean for some window timeframe, e.g. for temperature
weather['temperature'].rolling(window=2).mean()

0     NaN
1    44.0
2    48.5
3    48.5
4    42.0
5    42.0
6    53.0
7    49.0
8    43.0
Name: temperature, dtype: float64

In [39]:
# shifting some data for X steps
weather['temperature'].shift(1)

0     NaN
1    34.0
2    54.0
3    43.0
4    54.0
5    30.0
6    54.0
7    52.0
8    46.0
Name: temperature, dtype: float64

In [41]:
# .shift() is ususally used when we want to compare data YoY, WoW, etc. We can add an additional column, so calc is easier
weather['prev_temperature'] = weather['temperature'].shift(1)
weather

       date  temperature  cloudy snowing  prev_temperature
0  5/1/2017           34       1     Yes               NaN
1  5/2/2017           54       2     Yes              34.0
2  5/3/2017           43       3     Yes              54.0
3  5/4/2017           54       4     Yes              43.0
4  5/5/2017           30       5     Yes              54.0
5  5/6/2017           54       6      No              30.0
6  5/7/2017           52       7      No              54.0
7  5/8/2017           46       8      No              52.0
8  5/9/2017           40       9      No              46.0

In [43]:
illinois_df = data_df[data_df['state'] == 'Illinois'].copy()
illinois_df

              date      county     state     fips  cases  deaths
3       2020-01-24        Cook  Illinois  17031.0      1     0.0
6       2020-01-25        Cook  Illinois  17031.0      1     0.0
11      2020-01-26        Cook  Illinois  17031.0      1     0.0
16      2020-01-27        Cook  Illinois  17031.0      1     0.0
21      2020-01-28        Cook  Illinois  17031.0      1     0.0
...            ...         ...       ...      ...    ...     ...
843328  2020-12-19   Whiteside  Illinois  17195.0   4558   152.0
843329  2020-12-19        Will  Illinois  17197.0  48657   710.0
843330  2020-12-19  Williamson  Illinois  17199.0   4722   105.0
843331  2020-12-19   Winnebago  Illinois  17201.0  22759   338.0
843332  2020-12-19    Woodford  Illinois  17203.0   2491    43.0

[27012 rows x 6 columns]

In [54]:
# using .sample() to limit DF's data to X %%, to make calculations easier & faster
# it returns a random rows from source DF
illinois_df.sample(5)

              date     county     state     fips  cases  deaths
823845  2020-12-13      Union  Illinois  17181.0   1414    29.0
176108  2020-05-25     Shelby  Illinois  17173.0     16     1.0
212909  2020-06-06      Stark  Illinois  17175.0      3     0.0
294105  2020-07-02   Woodford  Illinois  17203.0     35     2.0
405929  2020-08-06  Jefferson  Illinois  17081.0    218    19.0

In [62]:
# random_state=XX param allows getting the same random rows all the time. It's like a stable random sample of data,
# to ensure data interpretability while running optimization tasks on different devices
illinois_df.sample(5, random_state=55)

              date      county     state     fips  cases  deaths
57039   2020-04-14       Henry  Illinois  17073.0     23     0.0
661509  2020-10-24        Cass  Illinois  17017.0    460    11.0
716675  2020-11-10    Franklin  Illinois  17055.0   1363    14.0
240764  2020-06-15       Henry  Illinois  17073.0     72     1.0
583760  2020-09-30  Williamson  Illinois  17199.0   1426    49.0

In [65]:
# use frac=.xx to indicate required sampling percentage
illinois_df.sample(frac=0.1, random_state=55)

              date      county     state     fips  cases  deaths
57039   2020-04-14       Henry  Illinois  17073.0     23     0.0
661509  2020-10-24        Cass  Illinois  17017.0    460    11.0
716675  2020-11-10    Franklin  Illinois  17055.0   1363    14.0
240764  2020-06-15       Henry  Illinois  17073.0     72     1.0
583760  2020-09-30  Williamson  Illinois  17199.0   1426    49.0
...            ...         ...       ...      ...    ...     ...
54389   2020-04-13      Saline  Illinois  17165.0      3     0.0
758914  2020-11-23       Perry  Illinois  17145.0    962    19.0
590239  2020-10-02   Whiteside  Illinois  17195.0    849    21.0
278258  2020-06-27        Cass  Illinois  17017.0    127     1.0
370530  2020-07-26     Douglas  Illinois  17041.0     94     1.0

[2701 rows x 6 columns]

#### - concatination of DataSets (concat, join, merge, etc)

In [77]:
illinois_df = data_df[data_df['state'] == 'Illinois'].copy()
washington_df = data_df[data_df['state'] == 'Washington'].copy()

In [72]:
# appending one DF to the end of another
pd.concat([washington_df, illinois_df])

              date      county       state     fips  cases  deaths
0       2020-01-21   Snohomish  Washington  53061.0      1     0.0
1       2020-01-22   Snohomish  Washington  53061.0      1     0.0
2       2020-01-23   Snohomish  Washington  53061.0      1     0.0
4       2020-01-24   Snohomish  Washington  53061.0      1     0.0
7       2020-01-25   Snohomish  Washington  53061.0      1     0.0
...            ...         ...         ...      ...    ...     ...
843328  2020-12-19   Whiteside    Illinois  17195.0   4558   152.0
843329  2020-12-19        Will    Illinois  17197.0  48657   710.0
843330  2020-12-19  Williamson    Illinois  17199.0   4722   105.0
843331  2020-12-19   Winnebago    Illinois  17201.0  22759   338.0
843332  2020-12-19    Woodford    Illinois  17203.0   2491    43.0

[38005 rows x 6 columns]

In [73]:
# or we can specify the axis for concat with axis
pd.concat([washington_df, illinois_df], axis=1)

,date,county,state,fips,cases,deaths,date,county,state,fips,cases,deaths
0,2020-01-21,Snohomish,Washington,53061.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
1,2020-01-22,Snohomish,Washington,53061.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
2,2020-01-23,Snohomish,Washington,53061.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
4,2020-01-24,Snohomish,Washington,53061.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
7,2020-01-25,Snohomish,Washington,53061.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
843328,NaN,NaN,NaN,NaN,NaN,NaN,2020-12-19,Whiteside,Illinois,17195.0,4558.0,152.0
843329,NaN,NaN,NaN,NaN,NaN,NaN,2020-12-19,Will,Illinois,17197.0,48657.0,710.0
843330,NaN,NaN,NaN,NaN,NaN,NaN,2020-12-19,Williamson,Illinois,17199.0,4722.0,105.0
843331,NaN,NaN,NaN,NaN,NaN,NaN,2020-12-19,Winnebago,Illinois,17201.0,22759.0,338.0
843332,NaN,NaN,NaN,NaN,NaN,NaN,2020-12-19,Woodford,Illinois,17203.0,2491.0,43.0

In [78]:
# but if we reset indices for both source DFs, we'll have the following: colums of the second DF will be added to the right 
washington_df.reset_index(inplace=True)
illinois_df.reset_index(inplace=True)
pd.concat([washington_df, illinois_df], axis=1)

,index,date,county,state,fips,cases,deaths,index,date,county,state,fips,cases,deaths
0,0.0,2020-01-21,Snohomish,Washington,53061.0,1.0,0.0,3,2020-01-24,Cook,Illinois,17031.0,1,0.0
1,1.0,2020-01-22,Snohomish,Washington,53061.0,1.0,0.0,6,2020-01-25,Cook,Illinois,17031.0,1,0.0
2,2.0,2020-01-23,Snohomish,Washington,53061.0,1.0,0.0,11,2020-01-26,Cook,Illinois,17031.0,1,0.0
3,4.0,2020-01-24,Snohomish,Washington,53061.0,1.0,0.0,16,2020-01-27,Cook,Illinois,17031.0,1,0.0
4,7.0,2020-01-25,Snohomish,Washington,53061.0,1.0,0.0,21,2020-01-28,Cook,Illinois,17031.0,1,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,843328,2020-12-19,Whiteside,Illinois,17195.0,4558,152.0
27008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,843329,2020-12-19,Will,Illinois,17197.0,48657,710.0
27009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,843330,2020-12-19,Williamson,Illinois,17199.0,4722,105.0
27010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,843331,2020-12-19,Winnebago,Illinois,17201.0,22759,338.0
27011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,843332,2020-12-19,Woodford,Illinois,17203.0,2491,43.0

In [79]:
left = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],
                    'data1': range(7),
                    'other_data': range(7)})
right = pd.DataFrame({'key': ['a', 'b', 'd'],
                    'data2': range(3),
                    'other_data': range(3)})

In [80]:
left

  key  data1  other_data
0   b      0           0
1   b      1           1
2   a      2           2
3   c      3           3
4   a      4           4
5   a      5           5
6   b      6           6

In [81]:
right

  key  data2  other_data
0   a      0           0
1   b      1           1
2   d      2           2

In [ ]:
pd.concat([right, left], axis=1, keys=['right', 'left'])

  right                  left
    key data2 other_data  key data1 other_data
0     a   0.0        0.0    b     0          0
1     b   1.0        1.0    b     1          1
2     d   2.0        2.0    a     2          2
3   NaN   NaN        NaN    c     3          3
4   NaN   NaN        NaN    a     4          4
5   NaN   NaN        NaN    a     5          5
6   NaN   NaN        NaN    b     6          6

In [88]:
pd.concat([left, right], keys=['left', 'right'], axis=1)

  left                  right
   key data1 other_data data2 other_data
0    b   0.0        0.0   NaN        NaN
1    b   1.0        1.0   NaN        NaN
2    a   2.0        2.0   NaN        NaN
3    c   3.0        3.0   NaN        NaN
4    a   4.0        4.0   NaN        NaN
5    a   5.0        5.0   NaN        NaN
6    b   6.0        6.0   NaN        NaN
a  NaN   NaN        NaN   0.0        0.0
b  NaN   NaN        NaN   1.0        1.0
d  NaN   NaN        NaN   2.0        2.0

In [86]:
# using .join() method, a SQL analogy
right.set_index('key', inplace=True)

In [87]:
right

     data2  other_data
key
a        0           0
b        1           1
d        2           2

In [90]:
# use lsuffix & rsuffix to rename fields with the same name
left.join(right, on='key', lsuffix='_left', rsuffix='_right')

  key  data1  other_data_left  data2  other_data_right
0   b      0                0    1.0               1.0
1   b      1                1    1.0               1.0
2   a      2                2    0.0               0.0
3   c      3                3    NaN               NaN
4   a      4                4    0.0               0.0
5   a      5                5    0.0               0.0
6   b      6                6    1.0               1.0

In [92]:
# we can define how to join, e.g. 'inner' join - we'll get only those lines where there's a match
left.join(right, on='key', lsuffix='_left', rsuffix='_right', how='inner')

  key  data1  other_data_left  data2  other_data_right
0   b      0                0      1                 1
1   b      1                1      1                 1
2   a      2                2      0                 0
4   a      4                4      0                 0
5   a      5                5      0                 0
6   b      6                6      1                 1

In [97]:
# merge allows joining DF's by different key fields
left = pd.DataFrame({'key_1': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],
                    'data1': range(7),
                    'other_data': range(7)})
right = pd.DataFrame({'key_2': ['a', 'b', 'd'],
                    'data2': range(3),
                    'other_data': range(3)})

In [98]:
left

  key_1  data1  other_data
0     b      0           0
1     b      1           1
2     a      2           2
3     c      3           3
4     a      4           4
5     a      5           5
6     b      6           6

In [99]:
right

  key_2  data2  other_data
0     a      0           0
1     b      1           1
2     d      2           2

In [101]:
pd.merge(left, right, left_on='key_1', right_on='key_2')

  key_1  data1  other_data_x key_2  data2  other_data_y
0     b      0             0     b      1             1
1     b      1             1     b      1             1
2     a      2             2     a      0             0
3     a      4             4     a      0             0
4     a      5             5     a      0             0
5     b      6             6     b      1             1

In [102]:
# difference bw .join() & .merge()
# .join() - we're joining left DF with right DF by index
# .merge() - allows to specify fields we're using for merge operation. Thus it's a more flexible .join()

In [103]:
pd.merge(left, right, left_on='key_1', right_on='key_2', how='outer', suffixes=("_l", "_r"))

  key_1  data1  other_data_l key_2  data2  other_data_r
0     a    2.0           2.0     a    0.0           0.0
1     a    4.0           4.0     a    0.0           0.0
2     a    5.0           5.0     a    0.0           0.0
3     b    0.0           0.0     b    1.0           1.0
4     b    1.0           1.0     b    1.0           1.0
5     b    6.0           6.0     b    1.0           1.0
6     c    3.0           3.0   NaN    NaN           NaN
7   NaN    NaN           NaN     d    2.0           2.0

#### - .apply()

In [105]:
# we use .apply() to run a specific/custom func by rows (axis=1) or by columns (axis=0)
# data_df.apply(function, axis=1)

In [104]:
data_df.head()

         date     county       state     fips  cases  deaths
0  2020-01-21  Snohomish  Washington  53061.0      1     0.0
1  2020-01-22  Snohomish  Washington  53061.0      1     0.0
2  2020-01-23  Snohomish  Washington  53061.0      1     0.0
3  2020-01-24       Cook    Illinois  17031.0      1     0.0
4  2020-01-24  Snohomish  Washington  53061.0      1     0.0

In [106]:
def row_to_str(row):
    return row['county'] + ' - ' + row['state']

In [107]:
data_df.apply(row_to_str, axis=1).head()

0    Snohomish - Washington
1    Snohomish - Washington
2    Snohomish - Washington
3           Cook - Illinois
4    Snohomish - Washington
dtype: object

In [108]:
# doing the same by using lambda func
data_df.apply(lambda row: row['county'] + ' - ' + row['state'], axis=1).head()

0    Snohomish - Washington
1    Snohomish - Washington
2    Snohomish - Washington
3           Cook - Illinois
4    Snohomish - Washington
dtype: object

In [109]:
# applying by column
data_df['cases'].apply(lambda x: x>10)

0         False
1         False
2         False
3         False
4         False
          ...
845872     True
845873     True
845874     True
845875     True
845876     True
Name: cases, Length: 845877, dtype: bool

In [110]:
data_df['cases > 10'] = data_df['cases'].apply(lambda x: x>10)

In [111]:
data_df

              date      county       state     fips  cases  deaths  cases > 10
0       2020-01-21   Snohomish  Washington  53061.0      1     0.0       False
1       2020-01-22   Snohomish  Washington  53061.0      1     0.0       False
2       2020-01-23   Snohomish  Washington  53061.0      1     0.0       False
3       2020-01-24        Cook    Illinois  17031.0      1     0.0       False
4       2020-01-24   Snohomish  Washington  53061.0      1     0.0       False
...            ...         ...         ...      ...    ...     ...         ...
845872  2020-12-19  Sweetwater     Wyoming  56037.0   2702    15.0        True
845873  2020-12-19       Teton     Wyoming  56039.0   1992     2.0        True
845874  2020-12-19       Uinta     Wyoming  56041.0   1406     7.0        True
845875  2020-12-19    Washakie     Wyoming  56043.0    694    11.0        True
845876  2020-12-19      Weston     Wyoming  56045.0    443     2.0        True

[845877 rows x 7 columns]

In [112]:
# we can agregate by columns, calculating sum or mean, and keep original amount of rows with result_type='broadcast'
data_df[['cases', 'fips']].apply(lambda x: x.mean())

cases     1773.395245
fips     31250.816249
dtype: float64

In [113]:
data_df[['cases', 'fips']].apply(lambda x: x.mean(), result_type='broadcast')

              cases          fips
0       1773.395245  31250.816249
1       1773.395245  31250.816249
2       1773.395245  31250.816249
3       1773.395245  31250.816249
4       1773.395245  31250.816249
...             ...           ...
845872  1773.395245  31250.816249
845873  1773.395245  31250.816249
845874  1773.395245  31250.816249
845875  1773.395245  31250.816249
845876  1773.395245  31250.816249

[845877 rows x 2 columns]

####  - .to_datetime()

In [115]:
data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 845877 entries, 0 to 845876
Data columns (total 7 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   date        845877 non-null  object
 1   county      845877 non-null  object
 2   state       845877 non-null  object
 3   fips        837894 non-null  float64
 4   cases       845877 non-null  int64
 5   deaths      828052 non-null  float64
 6   cases > 10  845877 non-null  bool
dtypes: bool(1), float64(2), int64(1), object(3)
memory usage: 39.5+ MB

In [116]:
# converting object type to datetime, in order to be able to work with it - get a day, month, etc.
pd.to_datetime(data_df['date'])

0        2020-01-21
1        2020-01-22
2        2020-01-23
3        2020-01-24
4        2020-01-24
            ...
845872   2020-12-19
845873   2020-12-19
845874   2020-12-19
845875   2020-12-19
845876   2020-12-19
Name: date, Length: 845877, dtype: datetime64[ns]

In [ ]:
# specifying source format is allowed
pd.to_datetime(data_df['date'], format='%Y-%m-%d')

0        2020-01-21
1        2020-01-22
2        2020-01-23
3        2020-01-24
4        2020-01-24
            ...
845872   2020-12-19
845873   2020-12-19
845874   2020-12-19
845875   2020-12-19
845876   2020-12-19
Name: date, Length: 845877, dtype: datetime64[ns]

In [121]:
data_df['date'] = pd.to_datetime(data_df['date'], format='%Y-%m-%d')

In [122]:
data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 845877 entries, 0 to 845876
Data columns (total 7 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   date        845877 non-null  datetime64[ns]
 1   county      845877 non-null  object
 2   state       845877 non-null  object
 3   fips        837894 non-null  float64
 4   cases       845877 non-null  int64
 5   deaths      828052 non-null  float64
 6   cases > 10  845877 non-null  bool
dtypes: bool(1), datetime64[ns](1), float64(2), int64(1), object(2)
memory usage: 39.5+ MB

In [124]:
# now we can have access to many datetime methods - weekday, year, day, etc.
dir(data_df['date'].dt)

['__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__frozen',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_accessors',
 '_add_delegate_accessors',
 '_constructor',
 '_delegate_method',
 '_delegate_property_get',
 '_delegate_property_set',
 '_dir_additions',
 '_dir_deletions',
 '_freeze',
 '_get_values',
 '_hidden_attrs',
 '_parent',
 '_reset_cache',
 'as_unit',
 'ceil',
 'date',
 'day',
 'day_name',
 'day_of_week',
 'day_of_year',
 'dayofweek',
 'dayofyear',
 'days_in_month',
 'daysinmonth',
 'floor',
 'freq',
 'hour',
 'is_leap_year',
 'is_month_end',
 'is_month_start',
 'is_quarter_end',
 'is_quarter_start',
 'is_year_end',
 'is_year_start',
 'isocalendar',
 'microsecond',
 'minute',
 'month',
 'month_name',
 'nanosecond',
 'normalize',
 'quarter',
 'round',
 'second',
 'strftime',
 'time',
 'timetz',
 'to_period',
 'to_pydatetime',
 'tz',
 'tz_convert',
 'tz_localize',
 'unit',
 'weekday',
 'year']

####  - pivot vs pivot_table

In [132]:
weather = pd.DataFrame({'date': ['5/1/2017', '5/2/2017', '5/3/2017', '5/1/2017', '5/2/2017', '5/3/2017', '5/1/2017', '5/2/2017', '5/3/2017'],
                        'city': ['New York', 'New York', 'New York', 'London', 'London', 'London', 'Tokio', 'Tokio', 'Tokio'],
                        'temperature': [34, 54, 43, 54, 30, 54, 52, 46, 40],
                        'cloudy': [1, 2, 3, 4, 5, 6, 7, 8, 9],
                        'snowing': ['Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No']})

In [133]:
weather

       date      city  temperature  cloudy snowing
0  5/1/2017  New York           34       1     Yes
1  5/2/2017  New York           54       2     Yes
2  5/3/2017  New York           43       3     Yes
3  5/1/2017    London           54       4     Yes
4  5/2/2017    London           30       5     Yes
5  5/3/2017    London           54       6      No
6  5/1/2017     Tokio           52       7      No
7  5/2/2017     Tokio           46       8      No
8  5/3/2017     Tokio           40       9      No

In [134]:
# we structure/reshape source data as we want by using .pivot(). Data agregation is NOT supported - use pivot_table()
weather.pivot(index='date', columns='city', values='temperature')

city      London  New York  Tokio
date
5/1/2017      54        34     52
5/2/2017      30        54     46
5/3/2017      54        43     40

In [136]:
# if we need to agregate, we have to use .pivot_table
weather.pivot_table(index='snowing', columns='city', values='temperature', aggfunc='sum', fill_value=0)

city     London  New York  Tokio
snowing
No           54         0    138
Yes          84       131      0