### Exploring YouTube videos's data set:
#### - calculate unique video categories
#### - calculate mean view for each category
#### - define a separate dataset for top-liked video for each category, save it to a .csv

In [69]:
import pandas as pd
import numpy as np

In [3]:
yt_df = pd.read_csv('data/youtube_videos.csv')

In [5]:
# exploring data
yt_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39235 entries, 0 to 39234
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   video_id           38916 non-null  object
 1   title              38916 non-null  object
 2   channel_title      38916 non-null  object
 3   category_id        38916 non-null  float64
 4   publish_time       38916 non-null  object
 5   tags               38916 non-null  object
 6   views              38916 non-null  float64
 7   likes              38916 non-null  float64
 8   dislikes           38916 non-null  float64
 9   comment_count      38916 non-null  float64
 10  thumbnail_link     38916 non-null  object
 11  comments_disabled  38916 non-null  object
 12  description        38304 non-null  object
dtypes: float64(5), object(8)
memory usage: 3.9+ MB

In [7]:
yt_df.head(10)

,video_id,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,description
0,Jw1Y-zhQURU,John Lewis Christmas Ad 2017 - #MozTheMonster,John Lewis,26.0,2017-11-10T07:38:29.000Z,"christmas|""john lewis christmas""|""john lewis""|...",7224515.0,55681.0,10247.0,9479.0,https://i.ytimg.com/vi/Jw1Y-zhQURU/default.jpg,False,Click here to continue the story and make your...
1,3s1rvMFUweQ,Taylor Swift: …Ready for It? (Live) - SNL,Saturday Night Live,24.0,2017-11-12T06:24:44.000Z,"SNL|""Saturday Night Live""|""SNL Season 43""|""Epi...",1053632.0,25561.0,2294.0,2757.0,https://i.ytimg.com/vi/3s1rvMFUweQ/default.jpg,False,Musical guest Taylor Swift performs …Ready for...
2,n1WpP7iowLc,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10.0,2017-11-10T17:00:03.000Z,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579.0,787420.0,43420.0,125882.0,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,Eminem's new track Walk on Water ft. Beyoncé i...
3,PUTEiSjKwJU,Goals from Salford City vs Class of 92 and Fri...,Salford City Football Club,17.0,2017-11-13T02:30:38.000Z,"Salford City FC|""Salford City""|""Salford""|""Clas...",27833.0,193.0,12.0,37.0,https://i.ytimg.com/vi/PUTEiSjKwJU/default.jpg,False,Salford drew 4-4 against the Class of 92 and F...
4,rHwDegptbI4,Dashcam captures truck's near miss with child ...,Cute Girl Videos,25.0,2017-11-13T01:45:13.000Z,[none],9815.0,30.0,2.0,30.0,https://i.ytimg.com/vi/rHwDegptbI4/default.jpg,False,Dashcam captures truck's near miss with child ...
5,AumaWl0TNBo,How My Relationship Started!,PointlessBlogVlogs,24.0,2017-11-11T17:00:00.000Z,"pointlessblog|""pointlessblogtv""|""pointlessblog...",1182775.0,52708.0,1431.0,2333.0,https://i.ytimg.com/vi/AumaWl0TNBo/default.jpg,False,► HOW MY RELATIONSHIP STARTED!\n► PB Merch • h...
6,2Vv-BfVoq4g,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,10.0,2017-11-09T11:04:14.000Z,"edsheeran|""ed sheeran""|""acoustic""|""live""|""cove...",33523622.0,1634124.0,21082.0,85067.0,https://i.ytimg.com/vi/2Vv-BfVoq4g/default.jpg,False,🎧: https://ad.gt/yt-perfect\n💰: https://atlant...
7,-N5eucPMTTc,CHRISTMAS HAS GONE TO MY HEAD,MoreZoella,22.0,2017-11-10T19:19:43.000Z,"zoe sugg|""zoella""|""zoe""|""vlog""|""vlogging""|""vlo...",1164201.0,57309.0,749.0,624.0,https://i.ytimg.com/vi/-N5eucPMTTc/default.jpg,False,CHRISTMAS HAS GONE TO MY HEAD\nPrevious Vlog: ...
8,LMCuKltaY3M,Elbow - Golden Slumbers (John Lewis Advert 2017),ElbowVEVO,10.0,2017-11-10T08:00:01.000Z,"Elbow|""Golden""|""Slumbers""|""Polydor""|""Alternative""",154494.0,2163.0,147.0,211.0,https://i.ytimg.com/vi/LMCuKltaY3M/default.jpg,False,"“Golden Slumbers”, originally by The Beatles, ..."
9,9t9u_yPEidY,"Jennifer Lopez - Amor, Amor, Amor (Official Vi...",JenniferLopezVEVO,10.0,2017-11-10T15:00:00.000Z,"Jennifer Lopez ft. Wisin|""Jennifer Lopez ft. W...",9548677.0,190084.0,15015.0,11473.0,https://i.ytimg.com/vi/9t9u_yPEidY/default.jpg,False,"Jennifer Lopez ft. Wisin - Amor, Amor, Amor (O..."

In [17]:
# calculate unique video categories
yt_df['category_id'].unique().size

17

In [48]:
yt_df['category_id'].unique()

array([26., 24., 10., 17., 25., 22., 23., 28., 15., 27.,  1., 20.,  2.,
       nan, 19., 29., 43.])

In [53]:
# null values are present in the data set
yt_df[yt_df['category_id'].isnull()]

,video_id,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,description
206,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
207,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
208,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
630,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
631,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
37755,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37756,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38732,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38912,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39088,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [54]:
# cleaning null rows and saving into a separate dataset, just in case
yt_df_no_null_rows = yt_df.drop(index=yt_df[yt_df['category_id'].isnull()].index, axis=False)
yt_df_no_null_rows.isnull().value_counts(normalize=True)

video_id  title  channel_title  category_id  publish_time  tags   views  likes  dislikes  comment_count  thumbnail_link  comments_disabled  description
False     False  False          False        False         False  False  False  False     False          False           False              False          0.98
                                                                                                                                            True           0.02
Name: proportion, dtype: float64

In [30]:
# calculate mean view for each category
for cat in yt_df['category_id'].unique():
    mean_views = yt_df[yt_df['category_id'] == cat]['views'].mean()
    print(f'Category {cat}, mean view: {round(mean_views, 2):,}')

Category 26.0, mean view: 617,300.43
Category 24.0, mean view: 3,264,607.96
Category 10.0, mean view: 12,444,442.69
Category 17.0, mean view: 1,752,352.49
Category 25.0, mean view: 1,150,311.33
Category 22.0, mean view: 1,966,605.55
Category 23.0, mean view: 2,167,430.06
Category 28.0, mean view: 3,168,703.2
Category 15.0, mean view: 1,013,708.94
Category 27.0, mean view: 972,189.4
Category 1.0, mean view: 3,245,132.96
Category 20.0, mean view: 976,856.56
Category 2.0, mean view: 1,487,392.46
Category nan, mean view: nan
Category 19.0, mean view: 1,383,177.01
Category 29.0, mean view: 3,919,980.69
Category 43.0, mean view: 1,429,164.15

In [72]:
# using dict to display items sorted
views_per_cat = {}
for cat in yt_df['category_id'].unique():
    mean_views = yt_df[yt_df['category_id'] == cat]['views'].mean()
    views_per_cat[cat] = round(mean_views, 2)

views_per_cat_sorted = sorted(views_per_cat.items(), key=lambda x: x[1], reverse=True)

for item in views_per_cat_sorted:
    cat, views = item[0], item[1]
    if not(np.isnan(cat)):
        print(f'Category {cat}, mean view: {views:,}')

Category 10.0, mean view: 12,444,442.69
Category 1.0, mean view: 3,245,132.96
Category 28.0, mean view: 3,168,703.2
Category 23.0, mean view: 2,167,430.06
Category 22.0, mean view: 1,966,605.55
Category 17.0, mean view: 1,752,352.49
Category 29.0, mean view: 3,919,980.69
Category 24.0, mean view: 3,264,607.96
Category 2.0, mean view: 1,487,392.46
Category 43.0, mean view: 1,429,164.15
Category 19.0, mean view: 1,383,177.01
Category 25.0, mean view: 1,150,311.33
Category 15.0, mean view: 1,013,708.94
Category 20.0, mean view: 976,856.56
Category 27.0, mean view: 972,189.4
Category 26.0, mean view: 617,300.43

In [73]:
# define a separate dataset for top-liked video for each category, save it to .csv

In [107]:
most_liked_videos = []
for cat in yt_df['category_id'].unique():
    max_likes = yt_df[yt_df['category_id'] == cat]['likes'].max()
    print(f'Category {cat}, max likes: {round(max_likes, 2):,}')
    most_liked_videos.append((yt_df[(yt_df['category_id'] == cat) & (yt_df['likes'] == max_likes)]))

Category 26.0, max likes: 341,145.0
Category 24.0, max likes: 3,312,868.0
Category 10.0, max likes: 5,613,827.0
Category 17.0, max likes: 1,291,139.0
Category 25.0, max likes: 610,526.0
Category 22.0, max likes: 625,174.0
Category 23.0, max likes: 1,253,154.0
Category 28.0, max likes: 392,249.0
Category 15.0, max likes: 187,524.0
Category 27.0, max likes: 383,049.0
Category 1.0, max likes: 461,135.0
Category 20.0, max likes: 1,031,695.0
Category 2.0, max likes: 114,841.0
Category nan, max likes: nan
Category 19.0, max likes: 23,791.0
Category 29.0, max likes: 2,061,275.0
Category 43.0, max likes: 44,588.0

In [111]:
len(most_liked_videos)

17

In [ ]:
# uniting all separate df's from the list into a single one
top_liked_videos_df=pd.concat(most_liked_videos)

In [110]:
top_liked_videos_df

,video_id,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,description
12358,f6Egj7ncOi8,FULL FACE USING ONLY MY MOM'S MAKEUP Challenge...,NikkieTutorials,26.0,2017-12-29T22:23:18.000Z,"full face using only my mom's makeup|""full fac...",4.44e+06,3.41e+05,2.51e+03,1.40e+05,https://i.ytimg.com/vi/f6Egj7ncOi8/default.jpg,False,Make sure you subscribe to my channel and hit ...
8306,FlsCjmMhFmw,YouTube Rewind: The Shape of 2017 | #YouTubeRe...,YouTube Spotlight,24.0,2017-12-06T17:58:51.000Z,"Rewind|""Rewind 2017""|""youtube rewind 2017""|""#Y...",1.70e+08,3.31e+06,1.75e+06,8.45e+05,https://i.ytimg.com/vi/FlsCjmMhFmw/default.jpg,False,"YouTube Rewind 2017. Celebrating the videos, p..."
36939,7C2z4GqqS5E,BTS (방탄소년단) 'FAKE LOVE' Official MV,ibighit,10.0,2018-05-18T09:00:02.000Z,"BIGHIT|""빅히트""|""방탄소년단""|""BTS""|""BANGTAN""|""방탄""|""FAK...",1.23e+08,5.61e+06,2.07e+05,1.23e+06,https://i.ytimg.com/vi/7C2z4GqqS5E/default.jpg,False,BTS (방탄소년단) 'FAKE LOVE' Official MVDirector : ...
27842,Vm4Xn5vjqRA,"CRISTIANO RONALDO E FRED, O GRANDE ENCONTRO",Desimpedidos,17.0,2018-02-25T21:59:30.000Z,"desimpedidos|""bolivia""|""fred boiola""|""futebol ...",8.79e+06,1.29e+06,6.76e+03,9.17e+04,https://i.ytimg.com/vi/Vm4Xn5vjqRA/default.jpg,False,CHEGOU O DIA! Agora é o momento do nosso menin...
22558,yzshoDMBkqE,LOGAN PAUL RETURNS 📰 PEW NEWS📰,PewDiePie,25.0,2018-02-03T19:15:57.000Z,"pewdiepie|""pew""|""news""",1.13e+07,6.11e+05,2.58e+04,6.50e+04,https://i.ytimg.com/vi/yzshoDMBkqE/default.jpg,False,2 DAYS LEFT TO GET THAT MERCH: https://represe...
18365,IVzGsh0zRec,Holland(홀랜드) - 'Neverland (네버랜드)' M/V,HOLLAND,22.0,2018-01-21T15:00:01.000Z,"HOLLAND|""NEVERLAND""|""MV""|""NEWRELEASE""|""20180122""",6.54e+06,6.25e+05,3.16e+04,9.02e+04,https://i.ytimg.com/vi/IVzGsh0zRec/default.jpg,False,Apple Music - https://itunes.apple.com/us/albu...
9473,wzKL-bQKcgA,Anitta & J Balvin - Downtown (Official Lyric V...,Lele Pons,23.0,2017-12-14T18:30:08.000Z,anitta j balvin downtown official lyric video ...,4.35e+07,1.25e+06,3.87e+04,5.82e+04,https://i.ytimg.com/vi/wzKL-bQKcgA/default.jpg,False,WATCH DOWNTOWN MUSIC VIDEO ▶ https://youtu.be/...
23958,wbSwFU6tY1c,Falcon Heavy Test Flight,SpaceX,28.0,2018-02-06T21:03:04.000Z,[none],2.15e+07,3.92e+05,1.30e+04,3.95e+04,https://i.ytimg.com/vi/wbSwFU6tY1c/default.jpg,False,"Following its first test launch, Falcon Heavy ..."
18770,Y-iFgDK_D5s,The Smallest Bird you have ever seen,A Chick Called Albert,15.0,2018-01-21T00:10:07.000Z,"wren|""baby bird""|""incubating""|""nest""|""birdnest...",6.42e+06,1.88e+05,3.46e+03,1.85e+04,https://i.ytimg.com/vi/Y-iFgDK_D5s/default.jpg,False,By accident I got hold of two of the smallest ...
32576,jQNazsWnQKU,"Tyler, The Creator - OKRA","Tyler, The Creator",27.0,2018-03-29T16:07:11.000Z,"tyler the creator|""okra""|""flower boy""|""golf wa...",1.12e+07,3.83e+05,6.74e+03,1.95e+04,https://i.ytimg.com/vi/jQNazsWnQKU/default.jpg,False,"a throwaway song, lyrics below:check my bankro..."
25744,YBpdL9hSac4,Incredibles 2 - Olympics Sneak Peek,Disney•Pixar,1.0,2018-02-15T03:34:44.000Z,"Pixar|""Disney""|""Disney Pixar""|""Pixar Movie""|""A...",4.26e+07,4.61e+05,2.25e+04,5.03e+04,https://i.ytimg.com/vi/YBpdL9hSac4/default.jpg,False,The Incredibles are back on June 15. 💥 Watch ...
31921,x4CF5pruJz4,TORNEO DE YOUTUBERS #YTBattleRoyale - Fortnite...,elrubiusOMG,20.0,2018-03-26T00:44:31.000Z,"elrubius|""elrubiusomg""|""rubius""|""español""|""ris...",1.52e+07,1.03e+06,1.71e+04,2.31e+04,https://i.ytimg.com/vi/x4CF5pruJz4/default.jpg,False,Like por el HYPE\nMuchas gracias a todos por e...
10751,muAPJiMho2Y,DELIT DE FUITE - le Justicier de Noël,CHRIS-RS,2.0,2017-12-15T16:00:03.000Z,"Z800|""Z800E""|""KAWASAKI""|""PARIS""|""GOPRO""|""CAM""|...",3.64e+06,1.15e+05,1.21e+03,1.21e+04,https://i.ytimg.com/vi/muAPJiMho2Y/default.jpg,False,"Et bien oui...encore un délit de fuite, je sui..."
3432,r15_6z9xryo,Inside The World's Only Private Boeing 787 Dre...,Sam Chui,19.0,2017-11-17T13:01:28.000Z,"Boeing787|""Sam Chui""|""B787""|""Private Jet""|""Bus...",3.15e+06,2.38e+04,2.43e+03,2.36e+03,https://i.ytimg.com/vi/r15_6z9xryo/default.jpg,False,Join me for a tour of the World's First and On...
16503,oWjxSkJpxFU,Suicide: Be Here Tomorrow.,Logan Paul Vlogs,29.0,2018-01-24T18:30:01.000Z,"logan paul vlog|""logan paul""|""logan""|""paul""|""l...",2.67e+07,2.06e+06,5.46e+05,7.05e+05,https://i.ytimg.com/vi/oWjxSkJpxFU/default.jpg,False,National Suicide Prevention Lifeline\nCall 1-8...
39185,JtIY1Naxg0M,Game of Zones - S5E7: NBA 1K,Bleacher Report,43.0,2018-05-24T21:00:01.000Z,"bleacher report|""br""|""nba""|""philadelphia 76ers...",1.71e+06,4.46e+04,3.60e+02,4.34e+03,https://i.ytimg.com/vi/JtIY1Naxg0M/default.jpg,False,NBA rookies are roasting each other over a gam...

In [112]:
# simulating saving to .csv file using sys module
import sys
top_liked_videos_df.to_csv(sys.stdout, index=False)

video_id,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,description
f6Egj7ncOi8,FULL FACE USING ONLY MY MOM'S MAKEUP Challenge | NikkieTutorials,NikkieTutorials,26.0,2017-12-29T22:23:18.000Z,"full face using only my mom's makeup|""full face using only""|""full face""|""makeup challenge""|""challenge""|""mom's makeup""|""kids makeup""|""full face using only kids makeup""|""natural makeup challenge""|""makeup""|""nikkietutorials""|""nikkie tutorials""|""nikkitutorials""|""nikki tutorials""|""nikkietutorials crying""|""how to""|""how to apply""|""epic fail""|""fail""|""cosmetics""|""beauty""|""look""|""transformation""|""drugstore""|""winter wonder week""|""mom's makeup challenge""|""natural makeup""|""natural""|""glowy""|""dewy""|""viral""|""beauty products""|""mom""",4439763.0,341145.0,2506.0,139582.0,https://i.ytimg.com/vi/f6Egj7ncOi8/default.jpg,False,"Make sure you subscribe to my channel and hit the notification bell, so you don’t miss any of my new videos → http://bit.ly/SubscribeNikkieTutorials\n\nAfter doing the Full Face Using Only Kids Makeup and Liquid Lipsticks, today after many requests I’m doing the FULL FACE USING ONLY MY MOM’S MAKEUP Challenge! Oh, sweet makeup memories… Hope you enjoy & thanks for watching!\n\nPlease let me know who created this challenge so I can tag them here!\n\n🏆 DON’T FORGET TO JOIN THE $350 SEPHORA GIFT CARD GIVEAWAY BY SUBSCRIBING, LIKING THIS VIDEO AND LEAVING A COMMENT!!! 🏆\n\n▷ Have you seen my previous video? BYE MAKEUP! GET UNREADY WITH ME! » https://youtu.be/oYmc98Tx0BA\n\n••••••••••••••••••••••••••••••••••••••••­­­•••••••••••\n\n▷ LET’S BECOME FRIENDS!!\nBLOG ‣ http://www.nikkietutorials.com\nTWITTER ‣ http://www.twitter.com/Nikkietutorials\nINSTAGRAM ‣ https://instagram.com/nikkietutorials/\nSNAPCHAT ‣ https://www.snapchat.com/add/nikkietutorials\nFACEBOOK ‣ http://www.facebook.com/NikkieTutorials\n\n▷ OTHER VIDEOS YOU CAN CHECK OUT…….\n\n👑 THE POWER OF MAKEUP ► http://bit.ly/2scYIrE\n\n💑 BOYFRIEND DOES MY MAKEUP ► http://bit.ly/2r2K0yM\n\n🎀 THE NATURAL MAKEUP CHALLENGE! ► http://bit.ly/2pxxcVy\n\n🍑 POWER OF MAKEUP: KIM KARDASHIAN WEST ► http://bit.ly/2iz1RhT\n\n••••••••••••••••••••••••••••••••••••••••­­­•••••••••••\n\n♫ Music By ♫\nMusic by Chillhop: Chillhop Essentials - Fall 2017: https://youtu.be/FsKom00Xk-U\nListen on Spotify: http://bit.ly/ChillhopSpotify\n\nDisclaimer ‣ This video is NOT sponsored by any of the brands mentioned throughout this video. All thoughts mentioned are my own. Some affiliate links are used. They do not cost you anything, but I make a small percentage from the sale. Honesty is key on my channel, thank you for supporting me!\n\nʕ•ᴥ•ʔ I love you."
FlsCjmMhFmw,YouTube Rewind: The Shape of 2017 | #YouTubeRewind,YouTube Spotlight,24.0,2017-12-06T17:58:51.000Z,"Rewind|""Rewind 2017""|""youtube rewind 2017""|""#YouTubeRewind""|""Rewind 2016""|""Dan and Phil""|""Grace Helbig""|""HolaSoyGerman""|""Lilly Singh""|""Markiplier""|""Swoozie""|""Rhett Link""|""Liza Koshy""|""Dolan Twins""|""Lele Pons""|""Jake Paul""|""Logan Paul""|""KSI""|""Joey Graceffa""|""Casey Neistat""|""Poppy""|""Niana Guerrero""|""Daddy Yankee""|""Luis Fonsi""|""Ed Sheeran""|""Kendrick Lamar""|""Stephen Colbert""|""Fidget Spinners""|""Slime""|""Backpack Kid""|""April the Giraffe""|""#Rewind""|""Despacito""|""Shape of you""|""YouTubeRewind""|""I’m the One""|""Humble""",169884583.0,3312868.0,1753274.0,845233.0,https://i.ytimg.com/vi/FlsCjmMhFmw/default.jpg,False,"YouTube Rewind 2017. Celebrating the videos, people, music and memes that made 2017. #YouTubeRewind\n\nMeet the featured Creators in Rewind: https://rewind2017.withyoutube.com/creators\nSpend more time with your favorite Creators, videos and trends from 2017: https://yt.be/rewind2017\nTest your Rewind knowledge with our trivia game: http://yt.be/dejaview\n\nWatch trending videos from 2017: http://youtube.com/rewind\nSee the trends as they happen: http://youtube.com/trending\n\nWatch the Behind the Scenes video: https://youtu.be/OIQQ8jmsbMM  \nSee all the Easter Eggs: https://goo.gl/3U9otg\n\nMusic by The Hood Internet: https://www.youtube.com/thehoodinternet\n\nYouTube Rewind 2017 produced by Portal A"
7C2z4GqqS5E,BTS (방탄소년단) 'FAKE LOVE' Official MV,ibighit,10.0,2018-05-18T09:00:02.000Z,"BIGHIT|""빅히트""|""방탄소년단""|""BTS""|""BANGTAN""|""방탄""|""FAKE LOVE""|""FAKE_LOVE""|""fake love""",123010920.0,5613827.0,206892.0,1228655.0,https://i.ytimg.com/vi/7C2z4GqqS5E/default.jpg,False,"BTS (방탄소년단) 'FAKE LOVE' Official MVDirector : YongSeok Choi (Lumpens)Assistant Director : WonJu Lee, Guzza, HyeJeong Park, MinJe Jeong (Lumpens)Director of Photography : HyunWoo Nam(GDW)Gaffer : HyunSuk Song (Real Lighting)Art Director : JinSil Park Bona Kim (MU:E)Construction Manager : SukKi Song Special Effect : DemolitionBigHit Entertainment. Rights are reserved selectively in the video.Unauthorized reproduction is a violation of applicable laws. Manufactured by BigHit Entertainment, Seoul, KoreaConnect with BTS:http://www.ibighit.com http://twitter.com/BTS_bighit http://twitter.com/BTS_twt https://www.facebook.com/ibighit/http://www.facebook.com/bangtan.officialhttp://instagram.com/BTS.bighitofficialhttp://weibo.com/BTSbighitBU content certified by Big Hit Entertainment"
Vm4Xn5vjqRA,"CRISTIANO RONALDO E FRED, O GRANDE ENCONTRO",Desimpedidos,17.0,2018-02-25T21:59:30.000Z,"desimpedidos|""bolivia""|""fred boiola""|""futebol humor""|""futebol comedia""|""engraçado""|""futebol""|""zueira""|""gol""|""golaço""|""tricks""|""soccer""|""mitagem""|""dibre""|""drible""|""time""|""disimpedidos""|""disimpididos""|""desimpididos""|""Cristiano Ronaldo""|""CR7""|""CR7 da vida Real""",8788929.0,1291139.0,6762.0,91663.0,https://i.ytimg.com/vi/Vm4Xn5vjqRA/default.jpg,False,"CHEGOU O DIA! Agora é o momento do nosso menino brilhar. Clear levou o Fred para realizar o seu sonho de CONHECER O CRISTIANO RONALDO! Então, vai fazendo a pipoca, esquentando o café, que a mitagem vai começar! #ClearCR7Fred\n\nEste é o canal Desimpedidos. Pra quem ama futebol e zueira sem  limites, aqui  seu time é pequeno, o Paulo Baier é deus e o Cristiano Ronaldo é só mais um. \n\nCONTATO: contato@desimpedidos.com.br / imprensa@nwb.com.br"
yzshoDMBkqE,LOGAN PAUL RETURNS  📰 PEW NEWS📰,PewDiePie,25.0,2018-02-03T19:15:57.000Z,"pewdiepie|""pew""|""news""",11304442.0,610526.0,25837.0,65001.0,https://i.ytimg.com/vi/yzshoDMBkqE/default.jpg,False,2 DAYS LEFT TO GET THAT MERCH: https://represent.com/zerodeaths\n\nHeadphones::\nhttp://rzr.to/edgar\n\nChair::\nUSA & Asia: https://usa.clutchchairz.com/product/pewdiepie-edition-throttle-series/\nEurope: https://europe.clutchchairz.com/en/product/throttle-series-pewdiepie-edition/\nCanada: https://canada.clutchchairz.com/product/throttle-series-pewdiepie-edition/ ‎
IVzGsh0zRec,Holland(홀랜드) - 'Neverland (네버랜드)' M/V,HOLLAND,22.0,2018-01-21T15:00:01.000Z,"HOLLAND|""NEVERLAND""|""MV""|""NEWRELEASE""|""20180122""",6543327.0,625174.0,31577.0,90245.0,https://i.ytimg.com/vi/IVzGsh0zRec/default.jpg,False,Apple Music - https://itunes.apple.com/us/album/neverland-single/1337579750\n\nMore about HOLLAND @\nhttps://www.instagram.com/holland_vvv/\nhttps://www.youtube.com/c/HOLLANDOFFICIAL\nhttps://www.facebook.com/hollandofficial/ \nhttps://twitter.com/HOLLAND_vvv
wzKL-bQKcgA,Anitta & J Balvin - Downtown (Official Lyric Video) ft. Lele Pons & Juanpa Zurita,Lele Pons,23.0,2017-12-14T18:30:08.000Z,"anitta j balvin downtown official lyric video ft lele pons juanpa zurita|""anitta""|""balvin""|""downtown""|""official""|""lyric""|""video""|""ft""|""lele""|""pons""|""juanpa""|""zurita""|""spying on your boyfriend""|""secret santa""|""whose dog is it""|""Spying on Your Boyfriend | Lele Pons & Hannah Stocking""|""lelepons""|""hannahstocking""|""rudymancuso""|""inanna""|""anwar""|""sarkis""|""shots""|""shotsstudios""|""alesso""|""brazil""",43460605.0,1253154.0,38693.0,58235.0,https://i.ytimg.com/vi/wzKL-bQKcgA/default.jpg,False,WATCH DOWNTOWN MUSIC VIDEO ▶ https://youtu.be/wlS6Ix7mA0w\n\nDowntown (Spotify) ▶ http://spoti.fi/2zQ6mvp\n\nDowntown (Apple Music) ▶ http://apple.co/2zg1Wen\n\nDowntown (Everywhere) ▶ https://shots.com/Downtown\n\nSUBSCRIBE HERE ▶ http://www.youtube.com/channel/UCi9cDo6239RAzPpBZO9y5SA?sub_confirmation=1\n\nTHANKS FOR WATCHING! :) LIKE & SUBSCRIBE FOR MORE VIDEOS!\n-----------------------------------------------------------\nFIND ME ON:\nInstagram | http://instagram.com/lelepons\nTwitter | http://twitter.com/lelepons\nFacebook | http://facebook.com/lele\nSnapchat | http://snapchat.com/add/lelepons \n\nCAST: \nLele Pons | http://youtube.com/c/lelepons\nJuanpa Zurita | https://www.youtube.com/c/eljuanpazurita\n\nANITTA: \nYouTube | http://youtube.com/c/anitta\nInstagram | http://instagram.com/anitta\nTwitter | http://twitter.com/anitta\nFacebook | http://facebook.com/AnittaOficial\n\nJ BALVIN:\nYouTube | http://youtube.com/user/jbalvinVEVO\nInstagram | http://instagram.com/jbalvin\nTwitter | http://twitter.com/jbalvin\nFacebook | http://facebook.com/jbalvin\n\nChoreography:\nNick DeMoura | https://instagram.com/nickdemoura\n\nShots Studios Channels:\nAlesso | https://youtube.com/c/alesso\nAnitta | http://youtube.com/c/anitta\nAnwar Jibawi | http://youtube.com/c/anwar\nAwkward Puppets | http://youtube.com/c/awkwardpuppets\nHannah Stocking | http://youtube.com/c/hannahstocking\nInanna Sarkis | http://youtube.com/c/inanna\nLele Pons | http://youtube.com/c/lelepons\nMaejor | http://youtube.com/c/maejor\nMike Tyson | http://youtube.com/c/miketyson \nRudy Mancuso | http://youtube.com/c/rudymancuso\nShots Studios | http://youtube.com/c/shots\n\nLead Editor:\nAndrew Primavera \n\n#Lele\n#LelePons\n#JuanpaZurita\n#Downtown\n#Anitta\n#JBalvin
wbSwFU6tY1c,Falcon Heavy Test Flight,SpaceX,28.0,2018-02-06T21:03:04.000Z,[none],21530325.0,392249.0,13004.0,39468.0,https://i.ytimg.com/vi/wbSwFU6tY1c/default.jpg,False,"Following its first test launch, Falcon Heavy is now the most powerful operational rocket in the world by a factor of two. With the ability to lift into orbit nearly 64 metric tons (141,000 lb)---a mass greater than a 737 jetliner loaded with passengers, crew, luggage and fuel--Falcon Heavy can lift more than twice the payload of the next closest operational vehicle, the Delta IV Heavy, at one-third the cost. Falcon Heavy draws upon the proven heritage and reliability of Falcon 9. \n\nIts first stage is composed of three Falcon 9 nine-engine cores whose 27 Merlin engines together generate more than 5 million pounds of thrust at liftoff, equal to approximately eighteen 747 aircraft. Only the Saturn V moon rocket, last flown in 1973, delivered more payload to orbit. Falcon Heavy was designed from the outset to carry humans into space and restores the possibility of flying missions with crew to the Moon or Mars."
Y-iFgDK_D5s,The Smallest Bird you have ever seen,A Chick Called Albert,15.0,2018-01-21T00:10:07.000Z,"wren|""baby bird""|""incubating""|""nest""|""birdnest""|""hatching""|""incubator""|""sweet bird""|""little bird""|""little egg""|""egg""|""incubating eggs""|""einstein""|""smal bird""|""smallest bird""",6416920.0,187524.0,3461.0,18532.0,https://i.ytimg.com/vi/Y-iFgDK_D5s/default.jpg,False,By accident I got hold of two of the smallest eggs I have ever seen.\nShould I incubate them?\nWould I be able to raise a baby bird that would hatch from it?\n\nThe little bird is called a Wren. In my country it is the second smallest bird species there is.\n\nIt hatched so fast that I missed it.\nThe feeding was hard with my big human hands and very time-consuming. It took me about 80 feeding rounds per day to keep him healthy.\nBut in the end it worked.\n\n\nMore stories soon     cool if you subscribe\n\nThe incubator I used is a MS incubator\nMS incubators (made in Holland)\nhttps://www.broedmachine.nl/\nAnd in English \nhttps://www.broedmachine.nl/?___store=english&___from_store=dutch\n\nFor filming I used a canon EOSD7 and an I-phone 5s\n\nAll our music comes from audionetwork.com\nMusic in this video:\nCopos De Nieve by Christopher Slaski (PRS)\nFree Falling by Richard Kimmings (PRS) | Chris Egan (PRS)\nIn the Beginning by Paul Mottram (PRS)\nTime To Dream by Patrick Hawes (PRS)\nBoulevard Stroll by Keith Beauvais (PRS)\nLa Vie En Paris by Emily Lim (PRS)\n\nThank's for watching
jQNazsWnQKU,"Tyler, The Creator - OKRA","Tyler, The Creator",27.0,2018-03-29T16:07:11.000Z,"tyler the creator|""okra""|""flower boy""|""golf wang""|""golf le fleur""|""small bike jumps""",11240174.0,383049.0,6740.0,19451.0,https://i.ytimg.com/vi/jQNazsWnQKU/default.jpg,False,"a throwaway song, lyrics below:check my bankroll ayo 400k for vehiclepaintjob look like ashy ankles on djangointerior look mango shotgun grape he look like mayogolden voice on payroll neck all gold like kayo corpwe aim at dorks get out the waykeep them bucks in banks like yayoswampy niggas out the bayou pockets flooded yall be dilute watered downim big mac im quarter pound you chicken nuggetfuck it travel bag balenciaga 30,000 just for luggagefinancial advisor buggin flower boy is buzzingrammy nominated tell yo cousin aint no body fucking with himuno the shoe red with the blue look like a flag what the fuck it dogolf be the set no more OF like ron artest bitch we aim for your neckgive a fuck about you or your respect yeah that wayfuck your accolades but i made the cut like i pack a bladeyou could call me brush ive been making waves since ashley banks cousin had a fade but thats 92 im 91watts riot in my blood nigga whats up and that pussy pink like the drink in my cup halemonade yeah its minute maid i been getting paid pockets gaining weightyour bank statements on mary kate but thats up to youtell tim chalamet to come get at meskin glowing clear of acne diamonds see through so holographicred ones look like aidan mackey spent dinero like taxi driverhand made is that thing with tires but i rode my bike and vill tail behind me and he got the canon like he bagged mariah yeah we straight but if you wrinkle up the situation he will go grab the ironand he do what i says like simon no violence and my guy mixed like jambalayaman fuck with the fam we in japan bitch you’re a bum see you dont understandyeah i cut off some friends t where you been? bitch im in bel air been looking for landneed a spot in the hills not the beach need a pooljust to cool it i do need the grass not the sandgot enough rocks, see check my handand i got crack watch how i talkand its still wolf gang bitch watch how i bark wallace still tripping on shit that i boughtbut i really do not care the cost cause okradir: wolf haleydp: luis panch perez ( additional shots by wyatt)prod: happy place"
YBpdL9hSac4,Incredibles 2 - Olympics Sneak Peek,Disney•Pixar,1.0,2018-02-15T03:34:44.000Z,"Pixar|""Disney""|""Disney Pixar""|""Pixar Movie""|""Animation""|""incredibles""|""the incredibles""|""incredibles 2""|""jack jack""|""mr. incredible""|""mrs. incredible""|""frozone""|""samuel l. jackson""|""violet parr""|""dash parr""|""sneak peek""|""trailer""|""new movie""|""family movie""|""summer movie""|""first look""|""teaser""",42560014.0,461135.0,22464.0,50255.0,https://i.ytimg.com/vi/YBpdL9hSac4/default.jpg,False,"The Incredibles are back on June 15.  💥 Watch a brand-new sneak peek of Incredibles 2 now!\n\n---\n\nDisney/Pixar’s Incredibles 2 opens in theatres June 15!\n\nIn “Incredibles 2,” Helen (voice of Holly Hunter) is called on to lead a campaign to bring Supers back, while Bob (voice of Craig T. Nelson) navigates the day-to-day heroics of “normal” life at home with Violet (voice of Sarah Vowell), Dash (voice of Huck Milner) and baby Jack-Jack—whose superpowers are about to be discovered. Their mission is derailed, however, when a new villain emerges with a brilliant and dangerous plot that threatens everything. But the Parrs don’t shy away from a challenge, especially with Frozone (voice of Samuel L. Jackson) by their side. That’s what makes this family so Incredible. \n\nHashtag: #Incredibles2\nFacebook: https://www.facebook.com/PixarTheIncredibles/\nTwitter: https://twitter.com/TheIncredibles\nInstagram: https://www.instagram.com/theincredibles/"
x4CF5pruJz4,TORNEO DE YOUTUBERS #YTBattleRoyale - Fortnite - elrubiusOMG,elrubiusOMG,20.0,2018-03-26T00:44:31.000Z,"elrubius|""elrubiusomg""|""rubius""|""español""|""risa""|""risas""|""humor""|""comedia""|""entretenimiento""|""gracioso""|""juego""|""videojuegos""|""games""|""gaming""|""fortnite""|""ytbattleroyale""|""youtubers""|""torneo""|""torneo de youtubers""|""auronplay""|""wismichu""|""mangel""|""alexby""|""cancion""|""directo""|""entero""|""completo""",15241146.0,1031695.0,17093.0,23111.0,https://i.ytimg.com/vi/x4CF5pruJz4/default.jpg,False,"Like por el HYPE\nMuchas gracias a todos por estar conmigo en esta gran experiencia :) os quiero juapos\nEL DIRECTO EMPIEZA EN EL 3:35\nPara convertirte en patrocinador, entra aqui: https://gaming.youtube.com/channel/UCXazgXDIYyWH-yXLAkcrFxw"
muAPJiMho2Y,DELIT DE FUITE - le Justicier de Noël,CHRIS-RS,2.0,2017-12-15T16:00:03.000Z,"Z800|""Z800E""|""KAWASAKI""|""PARIS""|""GOPRO""|""CAM""|""MOTO""|""PARISIEN""|""STUNT""|""RS""|""YAMAHA""|""MT07""|""MT10""|""MT9""|""TMAX""|""H2""|""HJC""|""LORENZO""|""RIDER""|""MOTARD""|""CRASH""|""FRANCE""|""VLOG""|""YOUTUBE""|""delit de fuite""|""accident""|""crash""|""police""",3640031.0,114841.0,1209.0,12083.0,https://i.ytimg.com/vi/muAPJiMho2Y/default.jpg,False,"Et bien oui...encore un délit de fuite, je suis toujours là quand il y a de l'action. C'était parti pour une bonne journée, j'avais mis mon costume de Père Noël pour une nouvelle vidéo. Les gens étaient content de me voir habillé comme ça et de leur faire coucou. C'est après la Place Vendôme que cette scène dramatique arrive. Comme la dernière fois, je me devais d'essayer d'arrêter cette personne. J'ai eu des nouvelles de l'accidenté et il se remet sans trop de mal....\n\nMa Boutique : http://www.budnbee.com/chrisrs \n\nMon FACEBOOK : https://www.facebook.com/chris.rs.142\n\nMon INSTAGRAM : https://www.instagram.com/92izilife58/?hl=fr\n\nMUSIC :\nTwelve Titans Music - We Need Heroes - https://youtu.be/lWzrsNvqV94\n\nPosition Music - Lust For Power - https://youtu.be/95DxDR1z1fk\n\nMoto...Z800 FULL \nCam...Gopro Hero 5\nLogiciel de montage...Pinacle 20\n\nN'hésitez pas a me dire ce que vous en pensez en commentaire toutes critiques est Toujours bonne a prendre !!!\nAh oui, si vous aimez abonnez Vous, le Dieu de la Bécane vous le rendra !!!"
r15_6z9xryo,Inside The World's Only Private Boeing 787 Dreamliner!,Sam Chui,19.0,2017-11-17T13:01:28.000Z,"Boeing787|""Sam Chui""|""B787""|""Private Jet""|""Business Jet""|""Deer Air""|""Luxury Travel""|""UAS""|""Dubai Air Show""",3151902.0,23791.0,2434.0,2356.0,https://i.ytimg.com/vi/r15_6z9xryo/default.jpg,False,"Join me for a tour of the World's First and Only BBJ Boeing 787 Dreamliner in VVIP Configuration operated by Deer Jet.\n\nThis Private Boeing 787 was opened for display during the Dubai Air Show 2017. It is managed by UAS International Trip Support, the exclusive global charter management of the “Dream Jet”.\n\nFor full information, please visit my blog:\n\nhttps://samchui.com/2017/11/14/inside-worlds-private-dreamliner-bbj-b787/\n\nWhat do you think of this private VVIP Boeing 787 Dreamliner Dream Jet?\n\nMusic:\nGood For You by THBD https://soundcloud.com/thbdsultan\nCreative Commons — Attribution 3.0 Unported— CC BY 3.0 \nhttp://creativecommons.org/licenses/b...\nMusic promoted by Audio Library https://youtu.be/-K_YSjqKgvQ"

In [113]:
# second option - using groupby() method for mean views and top-liked videos
yt_df.groupby("category_id", sort=False)["views"].mean()

category_id
26.0    6.17e+05
24.0    3.26e+06
10.0    1.24e+07
17.0    1.75e+06
25.0    1.15e+06
22.0    1.97e+06
23.0    2.17e+06
28.0    3.17e+06
15.0    1.01e+06
27.0    9.72e+05
1.0     3.25e+06
20.0    9.77e+05
2.0     1.49e+06
19.0    1.38e+06
29.0    3.92e+06
43.0    1.43e+06
Name: views, dtype: float64

In [114]:
index_max_liked = yt_df.groupby("category_id")["likes"].transform(max) == yt_df["likes"]
yt_df[index_max_liked]

/var/folders/4s/q7yddbmx5x5cv8bjf0127cvr0000gn/T/ipykernel_67541/1852963538.py:1: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  index_max_liked = yt_df.groupby("category_id")["likes"].transform(max) == yt_df["likes"]

,video_id,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,description
3432,r15_6z9xryo,Inside The World's Only Private Boeing 787 Dre...,Sam Chui,19.0,2017-11-17T13:01:28.000Z,"Boeing787|""Sam Chui""|""B787""|""Private Jet""|""Bus...",3.15e+06,2.38e+04,2.43e+03,2.36e+03,https://i.ytimg.com/vi/r15_6z9xryo/default.jpg,False,Join me for a tour of the World's First and On...
8306,FlsCjmMhFmw,YouTube Rewind: The Shape of 2017 | #YouTubeRe...,YouTube Spotlight,24.0,2017-12-06T17:58:51.000Z,"Rewind|""Rewind 2017""|""youtube rewind 2017""|""#Y...",1.70e+08,3.31e+06,1.75e+06,8.45e+05,https://i.ytimg.com/vi/FlsCjmMhFmw/default.jpg,False,"YouTube Rewind 2017. Celebrating the videos, p..."
9473,wzKL-bQKcgA,Anitta & J Balvin - Downtown (Official Lyric V...,Lele Pons,23.0,2017-12-14T18:30:08.000Z,anitta j balvin downtown official lyric video ...,4.35e+07,1.25e+06,3.87e+04,5.82e+04,https://i.ytimg.com/vi/wzKL-bQKcgA/default.jpg,False,WATCH DOWNTOWN MUSIC VIDEO ▶ https://youtu.be/...
10751,muAPJiMho2Y,DELIT DE FUITE - le Justicier de Noël,CHRIS-RS,2.0,2017-12-15T16:00:03.000Z,"Z800|""Z800E""|""KAWASAKI""|""PARIS""|""GOPRO""|""CAM""|...",3.64e+06,1.15e+05,1.21e+03,1.21e+04,https://i.ytimg.com/vi/muAPJiMho2Y/default.jpg,False,"Et bien oui...encore un délit de fuite, je sui..."
12358,f6Egj7ncOi8,FULL FACE USING ONLY MY MOM'S MAKEUP Challenge...,NikkieTutorials,26.0,2017-12-29T22:23:18.000Z,"full face using only my mom's makeup|""full fac...",4.44e+06,3.41e+05,2.51e+03,1.40e+05,https://i.ytimg.com/vi/f6Egj7ncOi8/default.jpg,False,Make sure you subscribe to my channel and hit ...
16503,oWjxSkJpxFU,Suicide: Be Here Tomorrow.,Logan Paul Vlogs,29.0,2018-01-24T18:30:01.000Z,"logan paul vlog|""logan paul""|""logan""|""paul""|""l...",2.67e+07,2.06e+06,5.46e+05,7.05e+05,https://i.ytimg.com/vi/oWjxSkJpxFU/default.jpg,False,National Suicide Prevention Lifeline\nCall 1-8...
18365,IVzGsh0zRec,Holland(홀랜드) - 'Neverland (네버랜드)' M/V,HOLLAND,22.0,2018-01-21T15:00:01.000Z,"HOLLAND|""NEVERLAND""|""MV""|""NEWRELEASE""|""20180122""",6.54e+06,6.25e+05,3.16e+04,9.02e+04,https://i.ytimg.com/vi/IVzGsh0zRec/default.jpg,False,Apple Music - https://itunes.apple.com/us/albu...
18770,Y-iFgDK_D5s,The Smallest Bird you have ever seen,A Chick Called Albert,15.0,2018-01-21T00:10:07.000Z,"wren|""baby bird""|""incubating""|""nest""|""birdnest...",6.42e+06,1.88e+05,3.46e+03,1.85e+04,https://i.ytimg.com/vi/Y-iFgDK_D5s/default.jpg,False,By accident I got hold of two of the smallest ...
22558,yzshoDMBkqE,LOGAN PAUL RETURNS 📰 PEW NEWS📰,PewDiePie,25.0,2018-02-03T19:15:57.000Z,"pewdiepie|""pew""|""news""",1.13e+07,6.11e+05,2.58e+04,6.50e+04,https://i.ytimg.com/vi/yzshoDMBkqE/default.jpg,False,2 DAYS LEFT TO GET THAT MERCH: https://represe...
23958,wbSwFU6tY1c,Falcon Heavy Test Flight,SpaceX,28.0,2018-02-06T21:03:04.000Z,[none],2.15e+07,3.92e+05,1.30e+04,3.95e+04,https://i.ytimg.com/vi/wbSwFU6tY1c/default.jpg,False,"Following its first test launch, Falcon Heavy ..."
25744,YBpdL9hSac4,Incredibles 2 - Olympics Sneak Peek,Disney•Pixar,1.0,2018-02-15T03:34:44.000Z,"Pixar|""Disney""|""Disney Pixar""|""Pixar Movie""|""A...",4.26e+07,4.61e+05,2.25e+04,5.03e+04,https://i.ytimg.com/vi/YBpdL9hSac4/default.jpg,False,The Incredibles are back on June 15. 💥 Watch ...
27842,Vm4Xn5vjqRA,"CRISTIANO RONALDO E FRED, O GRANDE ENCONTRO",Desimpedidos,17.0,2018-02-25T21:59:30.000Z,"desimpedidos|""bolivia""|""fred boiola""|""futebol ...",8.79e+06,1.29e+06,6.76e+03,9.17e+04,https://i.ytimg.com/vi/Vm4Xn5vjqRA/default.jpg,False,CHEGOU O DIA! Agora é o momento do nosso menin...
31921,x4CF5pruJz4,TORNEO DE YOUTUBERS #YTBattleRoyale - Fortnite...,elrubiusOMG,20.0,2018-03-26T00:44:31.000Z,"elrubius|""elrubiusomg""|""rubius""|""español""|""ris...",1.52e+07,1.03e+06,1.71e+04,2.31e+04,https://i.ytimg.com/vi/x4CF5pruJz4/default.jpg,False,Like por el HYPE\nMuchas gracias a todos por e...
32576,jQNazsWnQKU,"Tyler, The Creator - OKRA","Tyler, The Creator",27.0,2018-03-29T16:07:11.000Z,"tyler the creator|""okra""|""flower boy""|""golf wa...",1.12e+07,3.83e+05,6.74e+03,1.95e+04,https://i.ytimg.com/vi/jQNazsWnQKU/default.jpg,False,"a throwaway song, lyrics below:check my bankro..."
36939,7C2z4GqqS5E,BTS (방탄소년단) 'FAKE LOVE' Official MV,ibighit,10.0,2018-05-18T09:00:02.000Z,"BIGHIT|""빅히트""|""방탄소년단""|""BTS""|""BANGTAN""|""방탄""|""FAK...",1.23e+08,5.61e+06,2.07e+05,1.23e+06,https://i.ytimg.com/vi/7C2z4GqqS5E/default.jpg,False,BTS (방탄소년단) 'FAKE LOVE' Official MVDirector : ...
39185,JtIY1Naxg0M,Game of Zones - S5E7: NBA 1K,Bleacher Report,43.0,2018-05-24T21:00:01.000Z,"bleacher report|""br""|""nba""|""philadelphia 76ers...",1.71e+06,4.46e+04,3.60e+02,4.34e+03,https://i.ytimg.com/vi/JtIY1Naxg0M/default.jpg,False,NBA rookies are roasting each other over a gam...